begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_package
DECL|package|net.sf.jabref.gui.util
package|package
name|net
operator|.
name|sf
operator|.
name|jabref
operator|.
name|gui
operator|.
name|util
package|;
end_package

begin_import
import|import
name|java
operator|.
name|awt
operator|.
name|FontMetrics
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|swing
operator|.
name|JTable
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|swing
operator|.
name|JTree
import|;
end_import

begin_class
DECL|class|GUIUtil
specifier|public
specifier|final
class|class
name|GUIUtil
block|{
DECL|method|GUIUtil ()
specifier|private
name|GUIUtil
parameter_list|()
block|{
comment|// Private constructor as all methods are static
block|}
comment|/**      * Update table row height to the best possible considering font size changes on the current platform      *      * http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=4760081      *      * @param table      */
DECL|method|correctRowHeight (JTable table)
specifier|public
specifier|static
name|void
name|correctRowHeight
parameter_list|(
name|JTable
name|table
parameter_list|)
block|{
comment|// Fix tree row height
name|FontMetrics
name|metrics
init|=
name|table
operator|.
name|getFontMetrics
argument_list|(
name|table
operator|.
name|getFont
argument_list|()
argument_list|)
decl_stmt|;
name|table
operator|.
name|setRowHeight
argument_list|(
name|Math
operator|.
name|max
argument_list|(
name|table
operator|.
name|getRowHeight
argument_list|()
argument_list|,
name|metrics
operator|.
name|getHeight
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
block|}
comment|/**      * Update tree row height to the best possible considering font size changes on the current platform      *      * http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=4760081      *      * @param table      */
DECL|method|correctRowHeight (JTree tree)
specifier|public
specifier|static
name|void
name|correctRowHeight
parameter_list|(
name|JTree
name|tree
parameter_list|)
block|{
comment|// Fix tree row height
name|FontMetrics
name|metrics
init|=
name|tree
operator|.
name|getFontMetrics
argument_list|(
name|tree
operator|.
name|getFont
argument_list|()
argument_list|)
decl_stmt|;
name|tree
operator|.
name|setRowHeight
argument_list|(
name|Math
operator|.
name|max
argument_list|(
name|tree
operator|.
name|getRowHeight
argument_list|()
argument_list|,
name|metrics
operator|.
name|getHeight
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

