begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_package
DECL|package|org.jabref.gui.maintable
package|package
name|org
operator|.
name|jabref
operator|.
name|gui
operator|.
name|maintable
package|;
end_package

begin_class
DECL|class|MainTablePreferences
specifier|public
class|class
name|MainTablePreferences
block|{
DECL|field|showGrid
specifier|private
specifier|final
name|boolean
name|showGrid
decl_stmt|;
DECL|field|columnPreferences
specifier|private
specifier|final
name|ColumnPreferences
name|columnPreferences
decl_stmt|;
DECL|field|resizeColumnsToFit
specifier|private
specifier|final
name|boolean
name|resizeColumnsToFit
decl_stmt|;
DECL|method|MainTablePreferences (boolean showGrid, ColumnPreferences columnPreferences, boolean resizeColumnsToFit)
specifier|public
name|MainTablePreferences
parameter_list|(
name|boolean
name|showGrid
parameter_list|,
name|ColumnPreferences
name|columnPreferences
parameter_list|,
name|boolean
name|resizeColumnsToFit
parameter_list|)
block|{
name|this
operator|.
name|showGrid
operator|=
name|showGrid
expr_stmt|;
name|this
operator|.
name|columnPreferences
operator|=
name|columnPreferences
expr_stmt|;
name|this
operator|.
name|resizeColumnsToFit
operator|=
name|resizeColumnsToFit
expr_stmt|;
block|}
DECL|method|getColumnPreferences ()
specifier|public
name|ColumnPreferences
name|getColumnPreferences
parameter_list|()
block|{
return|return
name|columnPreferences
return|;
block|}
DECL|method|resizeColumnsToFit ()
specifier|public
name|boolean
name|resizeColumnsToFit
parameter_list|()
block|{
return|return
name|resizeColumnsToFit
return|;
block|}
DECL|method|showGrid ()
specifier|public
name|boolean
name|showGrid
parameter_list|()
block|{
return|return
name|showGrid
return|;
block|}
block|}
end_class

end_unit

