begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_package
DECL|package|org.jabref.gui
package|package
name|org
operator|.
name|jabref
operator|.
name|gui
package|;
end_package

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|gui
operator|.
name|help
operator|.
name|HelpAction
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|gui
operator|.
name|importer
operator|.
name|ImportInspectionDialog
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|gui
operator|.
name|mergeentries
operator|.
name|MergeEntries
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|gui
operator|.
name|util
operator|.
name|WindowLocation
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|logic
operator|.
name|help
operator|.
name|HelpFile
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|logic
operator|.
name|l10n
operator|.
name|Localization
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|model
operator|.
name|entry
operator|.
name|BibEntry
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|preferences
operator|.
name|JabRefPreferences
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|swing
operator|.
name|*
import|;
end_import

begin_import
import|import
name|java
operator|.
name|awt
operator|.
name|*
import|;
end_import

begin_import
import|import
name|java
operator|.
name|awt
operator|.
name|event
operator|.
name|WindowAdapter
import|;
end_import

begin_import
import|import
name|java
operator|.
name|awt
operator|.
name|event
operator|.
name|WindowEvent
import|;
end_import

begin_class
DECL|class|DuplicateResolverDialog
specifier|public
class|class
name|DuplicateResolverDialog
extends|extends
name|JabRefDialog
block|{
DECL|enum|DuplicateResolverType
specifier|public
enum|enum
name|DuplicateResolverType
block|{
DECL|enumConstant|DUPLICATE_SEARCH
name|DUPLICATE_SEARCH
block|,
DECL|enumConstant|IMPORT_CHECK
name|IMPORT_CHECK
block|,
DECL|enumConstant|INSPECTION
name|INSPECTION
block|,
DECL|enumConstant|DUPLICATE_SEARCH_WITH_EXACT
name|DUPLICATE_SEARCH_WITH_EXACT
block|}
DECL|enum|DuplicateResolverResult
specifier|public
enum|enum
name|DuplicateResolverResult
block|{
DECL|enumConstant|NOT_CHOSEN
name|NOT_CHOSEN
block|,
DECL|enumConstant|KEEP_BOTH
name|KEEP_BOTH
block|,
DECL|enumConstant|KEEP_LEFT
name|KEEP_LEFT
block|,
DECL|enumConstant|KEEP_RIGHT
name|KEEP_RIGHT
block|,
DECL|enumConstant|AUTOREMOVE_EXACT
name|AUTOREMOVE_EXACT
block|,
DECL|enumConstant|KEEP_MERGE
name|KEEP_MERGE
block|,
DECL|enumConstant|BREAK
name|BREAK
block|}
DECL|field|helpButton
name|JButton
name|helpButton
init|=
operator|new
name|HelpAction
argument_list|(
name|Localization
operator|.
name|lang
argument_list|(
literal|"Help"
argument_list|)
argument_list|,
name|HelpFile
operator|.
name|FIND_DUPLICATES
argument_list|)
operator|.
name|getHelpButton
argument_list|()
decl_stmt|;
DECL|field|cancel
specifier|private
specifier|final
name|JButton
name|cancel
init|=
operator|new
name|JButton
argument_list|(
name|Localization
operator|.
name|lang
argument_list|(
literal|"Cancel"
argument_list|)
argument_list|)
decl_stmt|;
DECL|field|merge
specifier|private
specifier|final
name|JButton
name|merge
init|=
operator|new
name|JButton
argument_list|(
name|Localization
operator|.
name|lang
argument_list|(
literal|"Keep merged entry only"
argument_list|)
argument_list|)
decl_stmt|;
DECL|field|frame
specifier|private
specifier|final
name|JabRefFrame
name|frame
decl_stmt|;
DECL|field|options
specifier|private
specifier|final
name|JPanel
name|options
init|=
operator|new
name|JPanel
argument_list|()
decl_stmt|;
DECL|field|status
specifier|private
name|DuplicateResolverResult
name|status
init|=
name|DuplicateResolverResult
operator|.
name|NOT_CHOSEN
decl_stmt|;
DECL|field|me
specifier|private
name|MergeEntries
name|me
decl_stmt|;
DECL|method|DuplicateResolverDialog (JabRefFrame frame, BibEntry one, BibEntry two, DuplicateResolverType type)
specifier|public
name|DuplicateResolverDialog
parameter_list|(
name|JabRefFrame
name|frame
parameter_list|,
name|BibEntry
name|one
parameter_list|,
name|BibEntry
name|two
parameter_list|,
name|DuplicateResolverType
name|type
parameter_list|)
block|{
name|super
argument_list|(
operator|(
name|JFrame
operator|)
literal|null
argument_list|,
name|Localization
operator|.
name|lang
argument_list|(
literal|"Possible duplicate entries"
argument_list|)
argument_list|,
literal|true
argument_list|,
name|DuplicateResolverDialog
operator|.
name|class
argument_list|)
expr_stmt|;
name|this
operator|.
name|frame
operator|=
name|frame
expr_stmt|;
name|init
argument_list|(
name|one
argument_list|,
name|two
argument_list|,
name|type
argument_list|)
expr_stmt|;
block|}
DECL|method|DuplicateResolverDialog (ImportInspectionDialog dialog, BibEntry one, BibEntry two, DuplicateResolverType type)
specifier|public
name|DuplicateResolverDialog
parameter_list|(
name|ImportInspectionDialog
name|dialog
parameter_list|,
name|BibEntry
name|one
parameter_list|,
name|BibEntry
name|two
parameter_list|,
name|DuplicateResolverType
name|type
parameter_list|)
block|{
name|super
argument_list|(
name|dialog
argument_list|,
name|Localization
operator|.
name|lang
argument_list|(
literal|"Possible duplicate entries"
argument_list|)
argument_list|,
literal|true
argument_list|,
name|DuplicateResolverDialog
operator|.
name|class
argument_list|)
expr_stmt|;
name|this
operator|.
name|frame
operator|=
name|dialog
operator|.
name|getFrame
argument_list|()
expr_stmt|;
name|init
argument_list|(
name|one
argument_list|,
name|two
argument_list|,
name|type
argument_list|)
expr_stmt|;
block|}
DECL|method|init (BibEntry one, BibEntry two, DuplicateResolverType type)
specifier|private
name|void
name|init
parameter_list|(
name|BibEntry
name|one
parameter_list|,
name|BibEntry
name|two
parameter_list|,
name|DuplicateResolverType
name|type
parameter_list|)
block|{
name|JButton
name|both
decl_stmt|;
name|JButton
name|second
decl_stmt|;
name|JButton
name|first
decl_stmt|;
name|JButton
name|removeExact
init|=
literal|null
decl_stmt|;
switch|switch
condition|(
name|type
condition|)
block|{
case|case
name|DUPLICATE_SEARCH
case|:
name|first
operator|=
operator|new
name|JButton
argument_list|(
name|Localization
operator|.
name|lang
argument_list|(
literal|"Keep left"
argument_list|)
argument_list|)
expr_stmt|;
name|second
operator|=
operator|new
name|JButton
argument_list|(
name|Localization
operator|.
name|lang
argument_list|(
literal|"Keep right"
argument_list|)
argument_list|)
expr_stmt|;
name|both
operator|=
operator|new
name|JButton
argument_list|(
name|Localization
operator|.
name|lang
argument_list|(
literal|"Keep both"
argument_list|)
argument_list|)
expr_stmt|;
name|me
operator|=
operator|new
name|MergeEntries
argument_list|(
name|one
argument_list|,
name|two
argument_list|,
name|frame
operator|.
name|getCurrentBasePanel
argument_list|()
operator|.
name|getBibDatabaseContext
argument_list|()
operator|.
name|getMode
argument_list|()
argument_list|)
expr_stmt|;
break|break;
case|case
name|INSPECTION
case|:
name|first
operator|=
operator|new
name|JButton
argument_list|(
name|Localization
operator|.
name|lang
argument_list|(
literal|"Remove old entry"
argument_list|)
argument_list|)
expr_stmt|;
name|second
operator|=
operator|new
name|JButton
argument_list|(
name|Localization
operator|.
name|lang
argument_list|(
literal|"Remove entry from import"
argument_list|)
argument_list|)
expr_stmt|;
name|both
operator|=
operator|new
name|JButton
argument_list|(
name|Localization
operator|.
name|lang
argument_list|(
literal|"Keep both"
argument_list|)
argument_list|)
expr_stmt|;
name|me
operator|=
operator|new
name|MergeEntries
argument_list|(
name|one
argument_list|,
name|two
argument_list|,
name|Localization
operator|.
name|lang
argument_list|(
literal|"Old entry"
argument_list|)
argument_list|,
name|Localization
operator|.
name|lang
argument_list|(
literal|"From import"
argument_list|)
argument_list|,
name|frame
operator|.
name|getCurrentBasePanel
argument_list|()
operator|.
name|getBibDatabaseContext
argument_list|()
operator|.
name|getMode
argument_list|()
argument_list|)
expr_stmt|;
break|break;
case|case
name|DUPLICATE_SEARCH_WITH_EXACT
case|:
name|first
operator|=
operator|new
name|JButton
argument_list|(
name|Localization
operator|.
name|lang
argument_list|(
literal|"Keep left"
argument_list|)
argument_list|)
expr_stmt|;
name|second
operator|=
operator|new
name|JButton
argument_list|(
name|Localization
operator|.
name|lang
argument_list|(
literal|"Keep right"
argument_list|)
argument_list|)
expr_stmt|;
name|both
operator|=
operator|new
name|JButton
argument_list|(
name|Localization
operator|.
name|lang
argument_list|(
literal|"Keep both"
argument_list|)
argument_list|)
expr_stmt|;
name|removeExact
operator|=
operator|new
name|JButton
argument_list|(
name|Localization
operator|.
name|lang
argument_list|(
literal|"Automatically remove exact duplicates"
argument_list|)
argument_list|)
expr_stmt|;
name|me
operator|=
operator|new
name|MergeEntries
argument_list|(
name|one
argument_list|,
name|two
argument_list|,
name|frame
operator|.
name|getCurrentBasePanel
argument_list|()
operator|.
name|getBibDatabaseContext
argument_list|()
operator|.
name|getMode
argument_list|()
argument_list|)
expr_stmt|;
break|break;
default|default:
name|first
operator|=
operator|new
name|JButton
argument_list|(
name|Localization
operator|.
name|lang
argument_list|(
literal|"Import and remove old entry"
argument_list|)
argument_list|)
expr_stmt|;
name|second
operator|=
operator|new
name|JButton
argument_list|(
name|Localization
operator|.
name|lang
argument_list|(
literal|"Do not import entry"
argument_list|)
argument_list|)
expr_stmt|;
name|both
operator|=
operator|new
name|JButton
argument_list|(
name|Localization
operator|.
name|lang
argument_list|(
literal|"Import and keep old entry"
argument_list|)
argument_list|)
expr_stmt|;
name|me
operator|=
operator|new
name|MergeEntries
argument_list|(
name|one
argument_list|,
name|two
argument_list|,
name|Localization
operator|.
name|lang
argument_list|(
literal|"Old entry"
argument_list|)
argument_list|,
name|Localization
operator|.
name|lang
argument_list|(
literal|"From import"
argument_list|)
argument_list|,
name|frame
operator|.
name|getCurrentBasePanel
argument_list|()
operator|.
name|getBibDatabaseContext
argument_list|()
operator|.
name|getMode
argument_list|()
argument_list|)
expr_stmt|;
break|break;
block|}
if|if
condition|(
name|removeExact
operator|!=
literal|null
condition|)
block|{
name|options
operator|.
name|add
argument_list|(
name|removeExact
argument_list|)
expr_stmt|;
block|}
name|options
operator|.
name|add
argument_list|(
name|first
argument_list|)
expr_stmt|;
name|options
operator|.
name|add
argument_list|(
name|second
argument_list|)
expr_stmt|;
name|options
operator|.
name|add
argument_list|(
name|both
argument_list|)
expr_stmt|;
name|options
operator|.
name|add
argument_list|(
name|merge
argument_list|)
expr_stmt|;
name|options
operator|.
name|add
argument_list|(
name|Box
operator|.
name|createHorizontalStrut
argument_list|(
literal|5
argument_list|)
argument_list|)
expr_stmt|;
name|options
operator|.
name|add
argument_list|(
name|cancel
argument_list|)
expr_stmt|;
name|options
operator|.
name|add
argument_list|(
name|helpButton
argument_list|)
expr_stmt|;
name|first
operator|.
name|addActionListener
argument_list|(
name|e
lambda|->
name|buttonPressed
argument_list|(
name|DuplicateResolverResult
operator|.
name|KEEP_LEFT
argument_list|)
argument_list|)
expr_stmt|;
name|second
operator|.
name|addActionListener
argument_list|(
name|e
lambda|->
name|buttonPressed
argument_list|(
name|DuplicateResolverResult
operator|.
name|KEEP_RIGHT
argument_list|)
argument_list|)
expr_stmt|;
name|both
operator|.
name|addActionListener
argument_list|(
name|e
lambda|->
name|buttonPressed
argument_list|(
name|DuplicateResolverResult
operator|.
name|KEEP_BOTH
argument_list|)
argument_list|)
expr_stmt|;
name|merge
operator|.
name|addActionListener
argument_list|(
name|e
lambda|->
name|buttonPressed
argument_list|(
name|DuplicateResolverResult
operator|.
name|KEEP_MERGE
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|removeExact
operator|!=
literal|null
condition|)
block|{
name|removeExact
operator|.
name|addActionListener
argument_list|(
name|e
lambda|->
name|buttonPressed
argument_list|(
name|DuplicateResolverResult
operator|.
name|AUTOREMOVE_EXACT
argument_list|)
argument_list|)
expr_stmt|;
block|}
name|cancel
operator|.
name|addActionListener
argument_list|(
name|e
lambda|->
name|buttonPressed
argument_list|(
name|DuplicateResolverResult
operator|.
name|BREAK
argument_list|)
argument_list|)
expr_stmt|;
name|addWindowListener
argument_list|(
operator|new
name|WindowAdapter
argument_list|()
block|{
annotation|@
name|Override
specifier|public
name|void
name|windowClosing
parameter_list|(
name|WindowEvent
name|e
parameter_list|)
block|{
name|buttonPressed
argument_list|(
name|DuplicateResolverResult
operator|.
name|BREAK
argument_list|)
expr_stmt|;
block|}
block|}
argument_list|)
expr_stmt|;
name|getContentPane
argument_list|()
operator|.
name|add
argument_list|(
name|me
operator|.
name|getMergeEntryPanel
argument_list|()
argument_list|)
expr_stmt|;
name|getContentPane
argument_list|()
operator|.
name|add
argument_list|(
name|options
argument_list|,
name|BorderLayout
operator|.
name|SOUTH
argument_list|)
expr_stmt|;
name|pack
argument_list|()
expr_stmt|;
name|WindowLocation
name|pw
init|=
operator|new
name|WindowLocation
argument_list|(
name|this
argument_list|,
name|JabRefPreferences
operator|.
name|DUPLICATES_POS_X
argument_list|,
name|JabRefPreferences
operator|.
name|DUPLICATES_POS_Y
argument_list|,
name|JabRefPreferences
operator|.
name|DUPLICATES_SIZE_X
argument_list|,
name|JabRefPreferences
operator|.
name|DUPLICATES_SIZE_Y
argument_list|)
decl_stmt|;
name|pw
operator|.
name|displayWindowAtStoredLocation
argument_list|()
expr_stmt|;
name|both
operator|.
name|requestFocus
argument_list|()
expr_stmt|;
block|}
DECL|method|buttonPressed (DuplicateResolverResult result)
specifier|private
name|void
name|buttonPressed
parameter_list|(
name|DuplicateResolverResult
name|result
parameter_list|)
block|{
name|status
operator|=
name|result
expr_stmt|;
name|dispose
argument_list|()
expr_stmt|;
block|}
DECL|method|getSelected ()
specifier|public
name|DuplicateResolverResult
name|getSelected
parameter_list|()
block|{
return|return
name|status
return|;
block|}
DECL|method|getMergedEntry ()
specifier|public
name|BibEntry
name|getMergedEntry
parameter_list|()
block|{
return|return
name|me
operator|.
name|getMergeEntry
argument_list|()
return|;
block|}
block|}
end_class

end_unit

