begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  Copyright (C) 2003-2012 JabRef contributors.     This program is free software; you can redistribute it and/or modify     it under the terms of the GNU General Public License as published by     the Free Software Foundation; either version 2 of the License, or     (at your option) any later version.      This program is distributed in the hope that it will be useful,     but WITHOUT ANY WARRANTY; without even the implied warranty of     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the     GNU General Public License for more details.      You should have received a copy of the GNU General Public License along     with this program; if not, write to the Free Software Foundation, Inc.,     51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA. */
end_comment

begin_package
DECL|package|net.sf.jabref.autocompleter
package|package
name|net
operator|.
name|sf
operator|.
name|jabref
operator|.
name|autocompleter
package|;
end_package

begin_import
import|import
name|net
operator|.
name|sf
operator|.
name|jabref
operator|.
name|AuthorList
import|;
end_import

begin_import
import|import
name|net
operator|.
name|sf
operator|.
name|jabref
operator|.
name|BibtexEntry
import|;
end_import

begin_import
import|import
name|net
operator|.
name|sf
operator|.
name|jabref
operator|.
name|Globals
import|;
end_import

begin_import
import|import
name|net
operator|.
name|sf
operator|.
name|jabref
operator|.
name|JabRefPreferences
import|;
end_import

begin_comment
comment|/**  * Interprets the given values as names and stores them in different  * permutations so we can complete by beginning with last name or first name.  *   * @author kahlert, cordes  *   */
end_comment

begin_class
DECL|class|NameFieldAutoCompleter
specifier|public
class|class
name|NameFieldAutoCompleter
extends|extends
name|AbstractAutoCompleter
block|{
DECL|field|fieldNames
specifier|private
name|String
index|[]
name|fieldNames
decl_stmt|;
DECL|field|lastNameOnly
specifier|private
name|boolean
name|lastNameOnly
decl_stmt|;
DECL|field|prefix
specifier|private
name|String
name|prefix
init|=
literal|""
decl_stmt|;
DECL|field|autoCompFF
DECL|field|autoCompLF
specifier|private
name|boolean
name|autoCompFF
decl_stmt|,
name|autoCompLF
decl_stmt|;
DECL|field|caseSensitive
specifier|private
name|boolean
name|caseSensitive
init|=
literal|true
decl_stmt|;
comment|/** 	 * @see AutoCompleterFactory 	 */
DECL|method|NameFieldAutoCompleter (String fieldName)
specifier|protected
name|NameFieldAutoCompleter
parameter_list|(
name|String
name|fieldName
parameter_list|)
block|{
name|this
argument_list|(
operator|new
name|String
index|[]
block|{
name|fieldName
block|}
argument_list|,
literal|false
argument_list|)
expr_stmt|;
block|}
DECL|method|setCaseSensitive (boolean caseSensitive)
specifier|public
name|void
name|setCaseSensitive
parameter_list|(
name|boolean
name|caseSensitive
parameter_list|)
block|{
name|this
operator|.
name|caseSensitive
operator|=
name|caseSensitive
expr_stmt|;
block|}
DECL|method|NameFieldAutoCompleter (String[] fieldNames, boolean lastNameOnly)
specifier|public
name|NameFieldAutoCompleter
parameter_list|(
name|String
index|[]
name|fieldNames
parameter_list|,
name|boolean
name|lastNameOnly
parameter_list|)
block|{
name|this
operator|.
name|fieldNames
operator|=
name|fieldNames
expr_stmt|;
name|this
operator|.
name|lastNameOnly
operator|=
name|lastNameOnly
expr_stmt|;
if|if
condition|(
name|Globals
operator|.
name|prefs
operator|.
name|getBoolean
argument_list|(
literal|"autoCompFF"
argument_list|)
condition|)
block|{
name|autoCompFF
operator|=
literal|true
expr_stmt|;
name|autoCompLF
operator|=
literal|false
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|Globals
operator|.
name|prefs
operator|.
name|getBoolean
argument_list|(
literal|"autoCompLF"
argument_list|)
condition|)
block|{
name|autoCompFF
operator|=
literal|false
expr_stmt|;
name|autoCompLF
operator|=
literal|true
expr_stmt|;
block|}
else|else
block|{
name|autoCompFF
operator|=
literal|true
expr_stmt|;
name|autoCompLF
operator|=
literal|true
expr_stmt|;
block|}
block|}
DECL|method|isSingleUnitField ()
specifier|public
name|boolean
name|isSingleUnitField
parameter_list|()
block|{
return|return
literal|true
return|;
block|}
DECL|method|addBibtexEntry (String fieldValue, BibtexEntry entry)
specifier|public
name|void
name|addBibtexEntry
parameter_list|(
name|String
name|fieldValue
parameter_list|,
name|BibtexEntry
name|entry
parameter_list|)
block|{
name|addBibtexEntry
argument_list|(
name|entry
argument_list|)
expr_stmt|;
block|}
DECL|method|addBibtexEntry (BibtexEntry entry)
specifier|public
name|void
name|addBibtexEntry
parameter_list|(
name|BibtexEntry
name|entry
parameter_list|)
block|{
if|if
condition|(
name|entry
operator|!=
literal|null
condition|)
block|{
for|for
control|(
name|int
name|i
init|=
literal|0
init|;
name|i
operator|<
name|fieldNames
operator|.
name|length
condition|;
name|i
operator|++
control|)
block|{
name|String
name|fieldValue
init|=
name|entry
operator|.
name|getField
argument_list|(
name|fieldNames
index|[
name|i
index|]
argument_list|)
decl_stmt|;
if|if
condition|(
name|fieldValue
operator|!=
literal|null
condition|)
block|{
name|AuthorList
name|authorList
init|=
name|AuthorList
operator|.
name|getAuthorList
argument_list|(
name|fieldValue
argument_list|)
decl_stmt|;
for|for
control|(
name|int
name|j
init|=
literal|0
init|;
name|j
operator|<
name|authorList
operator|.
name|size
argument_list|()
condition|;
name|j
operator|++
control|)
block|{
name|AuthorList
operator|.
name|Author
name|author
init|=
name|authorList
operator|.
name|getAuthor
argument_list|(
name|j
argument_list|)
decl_stmt|;
if|if
condition|(
name|lastNameOnly
condition|)
block|{
name|addWordToIndex
argument_list|(
name|author
operator|.
name|getLastOnly
argument_list|()
argument_list|)
expr_stmt|;
block|}
else|else
block|{
if|if
condition|(
name|autoCompLF
condition|)
block|{
if|if
condition|(
name|Globals
operator|.
name|prefs
operator|.
name|get
argument_list|(
name|JabRefPreferences
operator|.
name|AUTOCOMPLETE_FIRSTNAME_MODE
argument_list|)
operator|.
name|equals
argument_list|(
name|JabRefPreferences
operator|.
name|AUTOCOMPLETE_FIRSTNAME_MODE_ONLY_ABBR
argument_list|)
condition|)
block|{
name|addWordToIndex
argument_list|(
name|author
operator|.
name|getLastFirst
argument_list|(
literal|true
argument_list|)
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|Globals
operator|.
name|prefs
operator|.
name|get
argument_list|(
name|JabRefPreferences
operator|.
name|AUTOCOMPLETE_FIRSTNAME_MODE
argument_list|)
operator|.
name|equals
argument_list|(
name|JabRefPreferences
operator|.
name|AUTOCOMPLETE_FIRSTNAME_MODE_ONLY_FULL
argument_list|)
condition|)
block|{
name|addWordToIndex
argument_list|(
name|author
operator|.
name|getLastFirst
argument_list|(
literal|false
argument_list|)
argument_list|)
expr_stmt|;
block|}
else|else
block|{
comment|// JabRefPreferences.AUTOCOMPLETE_FIRSTNAME_MODE_BOTH
name|addWordToIndex
argument_list|(
name|author
operator|.
name|getLastFirst
argument_list|(
literal|true
argument_list|)
argument_list|)
expr_stmt|;
name|addWordToIndex
argument_list|(
name|author
operator|.
name|getLastFirst
argument_list|(
literal|false
argument_list|)
argument_list|)
expr_stmt|;
block|}
block|}
if|if
condition|(
name|autoCompFF
condition|)
block|{
if|if
condition|(
name|Globals
operator|.
name|prefs
operator|.
name|get
argument_list|(
name|JabRefPreferences
operator|.
name|AUTOCOMPLETE_FIRSTNAME_MODE
argument_list|)
operator|.
name|equals
argument_list|(
name|JabRefPreferences
operator|.
name|AUTOCOMPLETE_FIRSTNAME_MODE_ONLY_ABBR
argument_list|)
condition|)
block|{
name|addWordToIndex
argument_list|(
name|author
operator|.
name|getFirstLast
argument_list|(
literal|true
argument_list|)
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|Globals
operator|.
name|prefs
operator|.
name|get
argument_list|(
name|JabRefPreferences
operator|.
name|AUTOCOMPLETE_FIRSTNAME_MODE
argument_list|)
operator|.
name|equals
argument_list|(
name|JabRefPreferences
operator|.
name|AUTOCOMPLETE_FIRSTNAME_MODE_ONLY_FULL
argument_list|)
condition|)
block|{
name|addWordToIndex
argument_list|(
name|author
operator|.
name|getFirstLast
argument_list|(
literal|false
argument_list|)
argument_list|)
expr_stmt|;
block|}
else|else
block|{
comment|// JabRefPreferences.AUTOCOMPLETE_FIRSTNAME_MODE_BOTH
name|addWordToIndex
argument_list|(
name|author
operator|.
name|getFirstLast
argument_list|(
literal|true
argument_list|)
argument_list|)
expr_stmt|;
name|addWordToIndex
argument_list|(
name|author
operator|.
name|getFirstLast
argument_list|(
literal|false
argument_list|)
argument_list|)
expr_stmt|;
block|}
block|}
block|}
block|}
block|}
block|}
block|}
block|}
DECL|method|complete (String str)
specifier|public
name|String
index|[]
name|complete
parameter_list|(
name|String
name|str
parameter_list|)
block|{
name|str
operator|=
name|str
operator|.
name|toLowerCase
argument_list|()
expr_stmt|;
name|int
name|index
init|=
name|str
operator|.
name|lastIndexOf
argument_list|(
literal|" and "
argument_list|)
decl_stmt|;
if|if
condition|(
name|index
operator|>=
literal|0
condition|)
block|{
name|prefix
operator|=
name|str
operator|.
name|substring
argument_list|(
literal|0
argument_list|,
name|index
operator|+
literal|5
argument_list|)
expr_stmt|;
name|str
operator|=
name|str
operator|.
name|substring
argument_list|(
name|index
operator|+
literal|5
argument_list|)
expr_stmt|;
block|}
else|else
name|prefix
operator|=
literal|""
expr_stmt|;
name|String
index|[]
name|res
init|=
name|super
operator|.
name|complete
argument_list|(
name|str
argument_list|)
decl_stmt|;
return|return
name|res
return|;
block|}
DECL|method|getFieldName ()
specifier|public
name|String
name|getFieldName
parameter_list|()
block|{
return|return
name|fieldNames
index|[
literal|0
index|]
return|;
block|}
annotation|@
name|Override
DECL|method|getPrefix ()
specifier|public
name|String
name|getPrefix
parameter_list|()
block|{
return|return
name|prefix
return|;
block|}
annotation|@
name|Override
DECL|method|addWordToIndex (String word)
specifier|public
name|void
name|addWordToIndex
parameter_list|(
name|String
name|word
parameter_list|)
block|{
name|super
operator|.
name|addWordToIndex
argument_list|(
name|word
operator|.
name|toLowerCase
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

