begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|//
end_comment

begin_comment
comment|// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
end_comment

begin_comment
comment|// See<a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
end_comment

begin_comment
comment|// Any modifications to this file will be lost upon recompilation of the source schema.
end_comment

begin_comment
comment|// Generated on: 2016.09.28 at 06:51:34 PM CEST
end_comment

begin_comment
comment|//
end_comment

begin_comment
comment|// This needs to be in the src/main/java to ensure that the Namespace is mapped to the prefix "mods"
end_comment

begin_comment
comment|// this can not be done by a gradle task at the moment
end_comment

begin_annotation
annotation|@
name|javax
operator|.
name|xml
operator|.
name|bind
operator|.
name|annotation
operator|.
name|XmlSchema
argument_list|(
name|namespace
operator|=
literal|"http://www.loc.gov/mods/v3"
argument_list|,
name|xmlns
operator|=
block|{
annotation|@
name|XmlNs
argument_list|(
name|prefix
operator|=
literal|"mods"
argument_list|,
name|namespaceURI
operator|=
literal|"http://www.loc.gov/mods/v3"
argument_list|)
block|}
argument_list|,
name|elementFormDefault
operator|=
name|javax
operator|.
name|xml
operator|.
name|bind
operator|.
name|annotation
operator|.
name|XmlNsForm
operator|.
name|QUALIFIED
argument_list|)
end_annotation

begin_package
DECL|package|net.sf.jabref.logic.importer.fileformat.mods
package|package
name|net
operator|.
name|sf
operator|.
name|jabref
operator|.
name|logic
operator|.
name|importer
operator|.
name|fileformat
operator|.
name|mods
package|;
end_package

begin_import
import|import
name|javax
operator|.
name|xml
operator|.
name|bind
operator|.
name|annotation
operator|.
name|XmlNs
import|;
end_import

end_unit

