begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  Copyright (C) 2003-2011 JabRef contributors.     This program is free software; you can redistribute it and/or modify     it under the terms of the GNU General Public License as published by     the Free Software Foundation; either version 2 of the License, or     (at your option) any later version.      This program is distributed in the hope that it will be useful,     but WITHOUT ANY WARRANTY; without even the implied warranty of     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the     GNU General Public License for more details.      You should have received a copy of the GNU General Public License along     with this program; if not, write to the Free Software Foundation, Inc.,     51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA. */
end_comment

begin_package
DECL|package|net.sf.jabref.export.layout.format
package|package
name|net
operator|.
name|sf
operator|.
name|jabref
operator|.
name|export
operator|.
name|layout
operator|.
name|format
package|;
end_package

begin_import
import|import
name|net
operator|.
name|sf
operator|.
name|jabref
operator|.
name|export
operator|.
name|layout
operator|.
name|ParamLayoutFormatter
import|;
end_import

begin_comment
comment|/**  * Layout formatter that puts in a default value (given as argument) if the field is empty.  * Empty means null or an empty string.  */
end_comment

begin_class
DECL|class|Default
specifier|public
class|class
name|Default
implements|implements
name|ParamLayoutFormatter
block|{
DECL|field|defValue
specifier|private
name|String
name|defValue
init|=
literal|""
decl_stmt|;
annotation|@
name|Override
DECL|method|setArgument (String arg)
specifier|public
name|void
name|setArgument
parameter_list|(
name|String
name|arg
parameter_list|)
block|{
name|this
operator|.
name|defValue
operator|=
name|arg
expr_stmt|;
block|}
annotation|@
name|Override
DECL|method|format (String fieldText)
specifier|public
name|String
name|format
parameter_list|(
name|String
name|fieldText
parameter_list|)
block|{
return|return
operator|(
name|fieldText
operator|!=
literal|null
operator|)
operator|&&
operator|(
operator|!
name|fieldText
operator|.
name|isEmpty
argument_list|()
operator|)
condition|?
name|fieldText
else|:
name|defValue
return|;
block|}
block|}
end_class

end_unit

