language: java
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8
sudo: false

before_install:
  - chmod +x gradlew

script:
  - ./gradlew check --info

after_success:
  - ./gradlew jacocoTestReport coveralls
