language: java
jdk:
  - oraclejdk8
sudo: false

before_install:
  - chmod +x gradlew

# allow gui testing on travis
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - ./gradlew test integrationTest

after_script:
  - ./gradlew jacocoTestReport coveralls
  - bash <(curl -s https://codecov.io/bash)

# cache gradle dependencies
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
