begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_package
DECL|package|org.jabref.gui.importer
package|package
name|org
operator|.
name|jabref
operator|.
name|gui
operator|.
name|importer
package|;
end_package

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|gui
operator|.
name|JabRefFrame
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|logic
operator|.
name|importer
operator|.
name|ParserResult
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|logic
operator|.
name|l10n
operator|.
name|Localization
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|swing
operator|.
name|*
import|;
end_import

begin_import
import|import
name|java
operator|.
name|awt
operator|.
name|*
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Objects
import|;
end_import

begin_comment
comment|/**  * Class for generating a dialog showing warnings from ParserResult  *  */
end_comment

begin_class
DECL|class|ParserResultWarningDialog
specifier|public
class|class
name|ParserResultWarningDialog
block|{
DECL|method|ParserResultWarningDialog ()
specifier|private
name|ParserResultWarningDialog
parameter_list|()
block|{     }
comment|/**      * Shows a dialog with the warnings from an import or open of a file      *      * @param parserResult - ParserResult for the current import/open      * @param jabRefFrame - the JabRefFrame      */
DECL|method|showParserResultWarningDialog (final ParserResult parserResult, final JabRefFrame jabRefFrame)
specifier|public
specifier|static
name|void
name|showParserResultWarningDialog
parameter_list|(
specifier|final
name|ParserResult
name|parserResult
parameter_list|,
specifier|final
name|JabRefFrame
name|jabRefFrame
parameter_list|)
block|{
name|Objects
operator|.
name|requireNonNull
argument_list|(
name|parserResult
argument_list|)
expr_stmt|;
name|Objects
operator|.
name|requireNonNull
argument_list|(
name|jabRefFrame
argument_list|)
expr_stmt|;
name|showParserResultWarningDialog
argument_list|(
name|parserResult
argument_list|,
name|jabRefFrame
argument_list|,
operator|-
literal|1
argument_list|)
expr_stmt|;
block|}
comment|/**      * Shows a dialog with the warnings from an import or open of a file      *      * @param parserResult - ParserResult for the current import/open      * @param jabRefFrame - the JabRefFrame      * @param dataBaseNumber - Database tab number to activate when showing the warning dialog      */
DECL|method|showParserResultWarningDialog (final ParserResult parserResult, final JabRefFrame jabRefFrame, final int dataBaseNumber)
specifier|public
specifier|static
name|void
name|showParserResultWarningDialog
parameter_list|(
specifier|final
name|ParserResult
name|parserResult
parameter_list|,
specifier|final
name|JabRefFrame
name|jabRefFrame
parameter_list|,
specifier|final
name|int
name|dataBaseNumber
parameter_list|)
block|{
name|Objects
operator|.
name|requireNonNull
argument_list|(
name|parserResult
argument_list|)
expr_stmt|;
name|Objects
operator|.
name|requireNonNull
argument_list|(
name|jabRefFrame
argument_list|)
expr_stmt|;
comment|// Return if no warnings
if|if
condition|(
operator|!
operator|(
name|parserResult
operator|.
name|hasWarnings
argument_list|()
operator|)
condition|)
block|{
return|return;
block|}
comment|// Switch tab if asked to do so
if|if
condition|(
name|dataBaseNumber
operator|>=
literal|0
condition|)
block|{
name|jabRefFrame
operator|.
name|showBasePanelAt
argument_list|(
name|dataBaseNumber
argument_list|)
expr_stmt|;
block|}
comment|// Generate string with warning texts
specifier|final
name|List
argument_list|<
name|String
argument_list|>
name|warnings
init|=
name|parserResult
operator|.
name|warnings
argument_list|()
decl_stmt|;
specifier|final
name|StringBuilder
name|dialogContent
init|=
operator|new
name|StringBuilder
argument_list|()
decl_stmt|;
name|int
name|warningCount
init|=
literal|1
decl_stmt|;
for|for
control|(
specifier|final
name|String
name|warning
range|:
name|warnings
control|)
block|{
name|dialogContent
operator|.
name|append
argument_list|(
name|String
operator|.
name|format
argument_list|(
literal|"%d. %s%n"
argument_list|,
name|warningCount
operator|++
argument_list|,
name|warning
argument_list|)
argument_list|)
expr_stmt|;
block|}
name|dialogContent
operator|.
name|deleteCharAt
argument_list|(
name|dialogContent
operator|.
name|length
argument_list|()
operator|-
literal|1
argument_list|)
expr_stmt|;
comment|// Generate dialog title
name|String
name|dialogTitle
decl_stmt|;
if|if
condition|(
name|dataBaseNumber
operator|<
literal|0
condition|)
block|{
name|dialogTitle
operator|=
name|Localization
operator|.
name|lang
argument_list|(
literal|"Warnings"
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|dialogTitle
operator|=
name|Localization
operator|.
name|lang
argument_list|(
literal|"Warnings"
argument_list|)
operator|+
literal|" ("
operator|+
name|parserResult
operator|.
name|getFile
argument_list|()
operator|.
name|get
argument_list|()
operator|.
name|getName
argument_list|()
operator|+
literal|")"
expr_stmt|;
block|}
comment|// Create JTextArea with JScrollPane
specifier|final
name|JTextArea
name|textArea
init|=
operator|new
name|JTextArea
argument_list|(
name|dialogContent
operator|.
name|toString
argument_list|()
argument_list|)
decl_stmt|;
specifier|final
name|JScrollPane
name|scrollPane
init|=
operator|new
name|JScrollPane
argument_list|(
name|textArea
argument_list|)
block|{
annotation|@
name|Override
specifier|public
name|Dimension
name|getPreferredSize
parameter_list|()
block|{
return|return
operator|new
name|Dimension
argument_list|(
literal|800
argument_list|,
name|Math
operator|.
name|min
argument_list|(
name|Math
operator|.
name|max
argument_list|(
literal|100
argument_list|,
name|warnings
operator|.
name|size
argument_list|()
operator|*
literal|15
argument_list|)
argument_list|,
literal|400
argument_list|)
argument_list|)
return|;
comment|// Guess a suitable height between 100 and 400
block|}
block|}
decl_stmt|;
comment|// Show dialog
name|JOptionPane
operator|.
name|showMessageDialog
argument_list|(
literal|null
argument_list|,
name|scrollPane
argument_list|,
name|dialogTitle
argument_list|,
name|JOptionPane
operator|.
name|WARNING_MESSAGE
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

