begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_package
DECL|package|net.sf.jabref.search.rules
package|package
name|net
operator|.
name|sf
operator|.
name|jabref
operator|.
name|search
operator|.
name|rules
package|;
end_package

begin_import
import|import
name|net
operator|.
name|sf
operator|.
name|jabref
operator|.
name|BibtexEntry
import|;
end_import

begin_import
import|import
name|net
operator|.
name|sf
operator|.
name|jabref
operator|.
name|search
operator|.
name|SearchRule
import|;
end_import

begin_comment
comment|/**  * Mock search rule that returns the values passed. Useful for testing.  */
end_comment

begin_class
DECL|class|MockSearchRule
specifier|public
class|class
name|MockSearchRule
implements|implements
name|SearchRule
block|{
DECL|field|result
specifier|private
specifier|final
name|boolean
name|result
decl_stmt|;
DECL|field|valid
specifier|private
specifier|final
name|boolean
name|valid
decl_stmt|;
DECL|method|MockSearchRule (boolean result, boolean valid)
specifier|public
name|MockSearchRule
parameter_list|(
name|boolean
name|result
parameter_list|,
name|boolean
name|valid
parameter_list|)
block|{
name|this
operator|.
name|result
operator|=
name|result
expr_stmt|;
name|this
operator|.
name|valid
operator|=
name|valid
expr_stmt|;
block|}
annotation|@
name|Override
DECL|method|applyRule (String query, BibtexEntry bibtexEntry)
specifier|public
name|boolean
name|applyRule
parameter_list|(
name|String
name|query
parameter_list|,
name|BibtexEntry
name|bibtexEntry
parameter_list|)
block|{
return|return
name|result
return|;
block|}
annotation|@
name|Override
DECL|method|validateSearchStrings (String query)
specifier|public
name|boolean
name|validateSearchStrings
parameter_list|(
name|String
name|query
parameter_list|)
block|{
return|return
name|valid
return|;
block|}
block|}
end_class

end_unit

