begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_package
DECL|package|org.jabref.gui.preferences
package|package
name|org
operator|.
name|jabref
operator|.
name|gui
operator|.
name|preferences
package|;
end_package

begin_import
import|import
name|javafx
operator|.
name|fxml
operator|.
name|FXML
import|;
end_import

begin_import
import|import
name|javafx
operator|.
name|scene
operator|.
name|control
operator|.
name|Button
import|;
end_import

begin_import
import|import
name|javafx
operator|.
name|scene
operator|.
name|control
operator|.
name|CheckBox
import|;
end_import

begin_import
import|import
name|javafx
operator|.
name|scene
operator|.
name|control
operator|.
name|ComboBox
import|;
end_import

begin_import
import|import
name|javafx
operator|.
name|scene
operator|.
name|control
operator|.
name|RadioButton
import|;
end_import

begin_import
import|import
name|javafx
operator|.
name|scene
operator|.
name|control
operator|.
name|TextField
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|gui
operator|.
name|JabRefFrame
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|gui
operator|.
name|push
operator|.
name|PushToApplication
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|gui
operator|.
name|util
operator|.
name|ViewModelListCellFactory
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|logic
operator|.
name|l10n
operator|.
name|Localization
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|preferences
operator|.
name|JabRefPreferences
import|;
end_import

begin_import
import|import
name|com
operator|.
name|airhacks
operator|.
name|afterburner
operator|.
name|views
operator|.
name|ViewLoader
import|;
end_import

begin_class
DECL|class|ExternalTabView
specifier|public
class|class
name|ExternalTabView
extends|extends
name|AbstractPreferenceTabView
implements|implements
name|PreferencesTab
block|{
DECL|field|eMailReferenceSubject
annotation|@
name|FXML
specifier|private
name|TextField
name|eMailReferenceSubject
decl_stmt|;
DECL|field|autoOpenAttachedFolders
annotation|@
name|FXML
specifier|private
name|CheckBox
name|autoOpenAttachedFolders
decl_stmt|;
DECL|field|pushToApplicationCombo
annotation|@
name|FXML
specifier|private
name|ComboBox
argument_list|<
name|PushToApplication
argument_list|>
name|pushToApplicationCombo
decl_stmt|;
DECL|field|citeCommand
annotation|@
name|FXML
specifier|private
name|TextField
name|citeCommand
decl_stmt|;
DECL|field|useTerminalDefault
annotation|@
name|FXML
specifier|private
name|RadioButton
name|useTerminalDefault
decl_stmt|;
DECL|field|useTerminalSpecial
annotation|@
name|FXML
specifier|private
name|RadioButton
name|useTerminalSpecial
decl_stmt|;
DECL|field|useTerminalCommand
annotation|@
name|FXML
specifier|private
name|TextField
name|useTerminalCommand
decl_stmt|;
DECL|field|useTerminalBrowse
annotation|@
name|FXML
specifier|private
name|Button
name|useTerminalBrowse
decl_stmt|;
DECL|field|usePDFAcrobat
annotation|@
name|FXML
specifier|private
name|RadioButton
name|usePDFAcrobat
decl_stmt|;
DECL|field|usePDFAcrobatCommand
annotation|@
name|FXML
specifier|private
name|TextField
name|usePDFAcrobatCommand
decl_stmt|;
DECL|field|usePDFAcrobatBrowse
annotation|@
name|FXML
specifier|private
name|Button
name|usePDFAcrobatBrowse
decl_stmt|;
DECL|field|usePDFSumatra
annotation|@
name|FXML
specifier|private
name|RadioButton
name|usePDFSumatra
decl_stmt|;
DECL|field|usePDFSumatraCommand
annotation|@
name|FXML
specifier|private
name|TextField
name|usePDFSumatraCommand
decl_stmt|;
DECL|field|usePDFSumatraBrowse
annotation|@
name|FXML
specifier|private
name|Button
name|usePDFSumatraBrowse
decl_stmt|;
DECL|field|useFileBrowserDefault
annotation|@
name|FXML
specifier|private
name|RadioButton
name|useFileBrowserDefault
decl_stmt|;
DECL|field|useFileBrowserSpecial
annotation|@
name|FXML
specifier|private
name|RadioButton
name|useFileBrowserSpecial
decl_stmt|;
DECL|field|useFileBrowserSpecialCommand
annotation|@
name|FXML
specifier|private
name|TextField
name|useFileBrowserSpecialCommand
decl_stmt|;
DECL|field|useFileBrowserSpecialBrowse
annotation|@
name|FXML
specifier|private
name|Button
name|useFileBrowserSpecialBrowse
decl_stmt|;
DECL|field|frame
specifier|private
specifier|final
name|JabRefFrame
name|frame
decl_stmt|;
DECL|method|ExternalTabView (JabRefPreferences preferences, JabRefFrame frame)
specifier|public
name|ExternalTabView
parameter_list|(
name|JabRefPreferences
name|preferences
parameter_list|,
name|JabRefFrame
name|frame
parameter_list|)
block|{
name|this
operator|.
name|preferences
operator|=
name|preferences
expr_stmt|;
name|this
operator|.
name|frame
operator|=
name|frame
expr_stmt|;
name|ViewLoader
operator|.
name|view
argument_list|(
name|this
argument_list|)
operator|.
name|root
argument_list|(
name|this
argument_list|)
operator|.
name|load
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Override
DECL|method|getTabName ()
specifier|public
name|String
name|getTabName
parameter_list|()
block|{
return|return
name|Localization
operator|.
name|lang
argument_list|(
literal|"External programs"
argument_list|)
return|;
block|}
DECL|method|initialize ()
specifier|public
name|void
name|initialize
parameter_list|()
block|{
name|ExternalTabViewModel
name|externalTabViewModel
init|=
operator|new
name|ExternalTabViewModel
argument_list|(
name|dialogService
argument_list|,
name|preferences
argument_list|,
name|frame
argument_list|)
decl_stmt|;
name|this
operator|.
name|viewModel
operator|=
name|externalTabViewModel
expr_stmt|;
operator|new
name|ViewModelListCellFactory
argument_list|<
name|PushToApplication
argument_list|>
argument_list|()
operator|.
name|withText
argument_list|(
name|PushToApplication
operator|::
name|getApplicationName
argument_list|)
operator|.
name|withIcon
argument_list|(
name|PushToApplication
operator|::
name|getIcon
argument_list|)
operator|.
name|install
argument_list|(
name|pushToApplicationCombo
argument_list|)
expr_stmt|;
name|eMailReferenceSubject
operator|.
name|textProperty
argument_list|()
operator|.
name|bindBidirectional
argument_list|(
name|externalTabViewModel
operator|.
name|eMailReferenceSubjectProperty
argument_list|()
argument_list|)
expr_stmt|;
name|autoOpenAttachedFolders
operator|.
name|selectedProperty
argument_list|()
operator|.
name|bindBidirectional
argument_list|(
name|externalTabViewModel
operator|.
name|autoOpenAttachedFoldersProperty
argument_list|()
argument_list|)
expr_stmt|;
name|pushToApplicationCombo
operator|.
name|itemsProperty
argument_list|()
operator|.
name|bind
argument_list|(
name|externalTabViewModel
operator|.
name|pushToApplicationsListProperty
argument_list|()
argument_list|)
expr_stmt|;
name|pushToApplicationCombo
operator|.
name|valueProperty
argument_list|()
operator|.
name|bindBidirectional
argument_list|(
name|externalTabViewModel
operator|.
name|selectedPushToApplication
argument_list|()
argument_list|)
expr_stmt|;
name|citeCommand
operator|.
name|textProperty
argument_list|()
operator|.
name|bindBidirectional
argument_list|(
name|externalTabViewModel
operator|.
name|citeCommandProperty
argument_list|()
argument_list|)
expr_stmt|;
name|useTerminalDefault
operator|.
name|selectedProperty
argument_list|()
operator|.
name|bindBidirectional
argument_list|(
name|externalTabViewModel
operator|.
name|useTerminalDefaultProperty
argument_list|()
argument_list|)
expr_stmt|;
name|useTerminalSpecial
operator|.
name|selectedProperty
argument_list|()
operator|.
name|bindBidirectional
argument_list|(
name|externalTabViewModel
operator|.
name|useTerminalSpecialProperty
argument_list|()
argument_list|)
expr_stmt|;
name|useTerminalCommand
operator|.
name|textProperty
argument_list|()
operator|.
name|bindBidirectional
argument_list|(
name|externalTabViewModel
operator|.
name|useTerminalCommandProperty
argument_list|()
argument_list|)
expr_stmt|;
name|useTerminalCommand
operator|.
name|disableProperty
argument_list|()
operator|.
name|bind
argument_list|(
name|useTerminalSpecial
operator|.
name|selectedProperty
argument_list|()
operator|.
name|not
argument_list|()
argument_list|)
expr_stmt|;
name|useTerminalBrowse
operator|.
name|disableProperty
argument_list|()
operator|.
name|bind
argument_list|(
name|useTerminalSpecial
operator|.
name|selectedProperty
argument_list|()
operator|.
name|not
argument_list|()
argument_list|)
expr_stmt|;
name|usePDFAcrobat
operator|.
name|selectedProperty
argument_list|()
operator|.
name|bindBidirectional
argument_list|(
name|externalTabViewModel
operator|.
name|usePDFAcrobatProperty
argument_list|()
argument_list|)
expr_stmt|;
name|usePDFAcrobatCommand
operator|.
name|textProperty
argument_list|()
operator|.
name|bindBidirectional
argument_list|(
name|externalTabViewModel
operator|.
name|usePDFAcrobatCommandProperty
argument_list|()
argument_list|)
expr_stmt|;
name|usePDFAcrobatCommand
operator|.
name|disableProperty
argument_list|()
operator|.
name|bind
argument_list|(
name|usePDFAcrobat
operator|.
name|selectedProperty
argument_list|()
operator|.
name|not
argument_list|()
argument_list|)
expr_stmt|;
name|usePDFAcrobatBrowse
operator|.
name|disableProperty
argument_list|()
operator|.
name|bind
argument_list|(
name|usePDFAcrobat
operator|.
name|selectedProperty
argument_list|()
operator|.
name|not
argument_list|()
argument_list|)
expr_stmt|;
name|usePDFSumatra
operator|.
name|selectedProperty
argument_list|()
operator|.
name|bindBidirectional
argument_list|(
name|externalTabViewModel
operator|.
name|usePDFSumatraProperty
argument_list|()
argument_list|)
expr_stmt|;
name|usePDFSumatraCommand
operator|.
name|textProperty
argument_list|()
operator|.
name|bindBidirectional
argument_list|(
name|externalTabViewModel
operator|.
name|usePDFSumatraCommandProperty
argument_list|()
argument_list|)
expr_stmt|;
name|usePDFSumatraCommand
operator|.
name|disableProperty
argument_list|()
operator|.
name|bind
argument_list|(
name|usePDFSumatra
operator|.
name|selectedProperty
argument_list|()
operator|.
name|not
argument_list|()
argument_list|)
expr_stmt|;
name|usePDFSumatraBrowse
operator|.
name|disableProperty
argument_list|()
operator|.
name|bind
argument_list|(
name|usePDFSumatra
operator|.
name|selectedProperty
argument_list|()
operator|.
name|not
argument_list|()
argument_list|)
expr_stmt|;
name|useFileBrowserDefault
operator|.
name|selectedProperty
argument_list|()
operator|.
name|bindBidirectional
argument_list|(
name|externalTabViewModel
operator|.
name|useFileBrowserDefaultProperty
argument_list|()
argument_list|)
expr_stmt|;
name|useFileBrowserSpecial
operator|.
name|selectedProperty
argument_list|()
operator|.
name|bindBidirectional
argument_list|(
name|externalTabViewModel
operator|.
name|useFileBrowserSpecialProperty
argument_list|()
argument_list|)
expr_stmt|;
name|useFileBrowserSpecialCommand
operator|.
name|textProperty
argument_list|()
operator|.
name|bindBidirectional
argument_list|(
name|externalTabViewModel
operator|.
name|useFileBrowserSpecialCommandProperty
argument_list|()
argument_list|)
expr_stmt|;
name|useFileBrowserSpecialCommand
operator|.
name|disableProperty
argument_list|()
operator|.
name|bind
argument_list|(
name|useFileBrowserSpecial
operator|.
name|selectedProperty
argument_list|()
operator|.
name|not
argument_list|()
argument_list|)
expr_stmt|;
name|useFileBrowserSpecialBrowse
operator|.
name|disableProperty
argument_list|()
operator|.
name|bind
argument_list|(
name|useFileBrowserSpecial
operator|.
name|selectedProperty
argument_list|()
operator|.
name|not
argument_list|()
argument_list|)
expr_stmt|;
block|}
annotation|@
name|FXML
DECL|method|pushToApplicationSettings ()
name|void
name|pushToApplicationSettings
parameter_list|()
block|{
operator|(
operator|(
name|ExternalTabViewModel
operator|)
name|viewModel
operator|)
operator|.
name|pushToApplicationSettings
argument_list|()
expr_stmt|;
block|}
annotation|@
name|FXML
DECL|method|manageExternalFileTypes ()
name|void
name|manageExternalFileTypes
parameter_list|()
block|{
operator|(
operator|(
name|ExternalTabViewModel
operator|)
name|viewModel
operator|)
operator|.
name|manageExternalFileTypes
argument_list|()
expr_stmt|;
block|}
annotation|@
name|FXML
DECL|method|useTerminalCommandBrowse ()
name|void
name|useTerminalCommandBrowse
parameter_list|()
block|{
operator|(
operator|(
name|ExternalTabViewModel
operator|)
name|viewModel
operator|)
operator|.
name|useTerminalCommandBrowse
argument_list|()
expr_stmt|;
block|}
annotation|@
name|FXML
DECL|method|usePDFAcrobatCommandBrowse ()
name|void
name|usePDFAcrobatCommandBrowse
parameter_list|()
block|{
operator|(
operator|(
name|ExternalTabViewModel
operator|)
name|viewModel
operator|)
operator|.
name|usePDFAcrobatCommandBrowse
argument_list|()
expr_stmt|;
block|}
annotation|@
name|FXML
DECL|method|usePDFSumatraCommandBrowse ()
name|void
name|usePDFSumatraCommandBrowse
parameter_list|()
block|{
operator|(
operator|(
name|ExternalTabViewModel
operator|)
name|viewModel
operator|)
operator|.
name|usePDFSumatraCommandBrowse
argument_list|()
expr_stmt|;
block|}
annotation|@
name|FXML
DECL|method|useFileBrowserSpecialCommandBrowse ()
name|void
name|useFileBrowserSpecialCommandBrowse
parameter_list|()
block|{
operator|(
operator|(
name|ExternalTabViewModel
operator|)
name|viewModel
operator|)
operator|.
name|useFileBrowserSpecialCommandBrowse
argument_list|()
expr_stmt|;
block|}
block|}
end_class

end_unit

