begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_package
DECL|package|org.jabref.gui.preferences
package|package
name|org
operator|.
name|jabref
operator|.
name|gui
operator|.
name|preferences
package|;
end_package

begin_import
import|import
name|javafx
operator|.
name|fxml
operator|.
name|FXML
import|;
end_import

begin_import
import|import
name|javafx
operator|.
name|scene
operator|.
name|Node
import|;
end_import

begin_import
import|import
name|javafx
operator|.
name|scene
operator|.
name|control
operator|.
name|Button
import|;
end_import

begin_import
import|import
name|javafx
operator|.
name|scene
operator|.
name|control
operator|.
name|CheckBox
import|;
end_import

begin_import
import|import
name|javafx
operator|.
name|scene
operator|.
name|control
operator|.
name|ComboBox
import|;
end_import

begin_import
import|import
name|javafx
operator|.
name|scene
operator|.
name|control
operator|.
name|RadioButton
import|;
end_import

begin_import
import|import
name|javafx
operator|.
name|scene
operator|.
name|control
operator|.
name|TextField
import|;
end_import

begin_import
import|import
name|javafx
operator|.
name|scene
operator|.
name|control
operator|.
name|ToggleGroup
import|;
end_import

begin_import
import|import
name|javafx
operator|.
name|scene
operator|.
name|layout
operator|.
name|VBox
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|Globals
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|gui
operator|.
name|DialogService
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|gui
operator|.
name|actions
operator|.
name|ActionFactory
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|gui
operator|.
name|actions
operator|.
name|StandardActions
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|gui
operator|.
name|help
operator|.
name|HelpAction
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|logic
operator|.
name|help
operator|.
name|HelpFile
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|logic
operator|.
name|l10n
operator|.
name|Localization
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|preferences
operator|.
name|JabRefPreferences
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|preferences
operator|.
name|NewLineSeperator
import|;
end_import

begin_import
import|import
name|com
operator|.
name|airhacks
operator|.
name|afterburner
operator|.
name|views
operator|.
name|ViewLoader
import|;
end_import

begin_class
DECL|class|FileTabView
specifier|public
class|class
name|FileTabView
extends|extends
name|VBox
implements|implements
name|PrefsTab
block|{
DECL|field|openLastStartup
annotation|@
name|FXML
specifier|private
name|CheckBox
name|openLastStartup
decl_stmt|;
DECL|field|backupOldFile
annotation|@
name|FXML
specifier|private
name|CheckBox
name|backupOldFile
decl_stmt|;
DECL|field|noWrapFiles
annotation|@
name|FXML
specifier|private
name|TextField
name|noWrapFiles
decl_stmt|;
DECL|field|resolveStringsBibTex
annotation|@
name|FXML
specifier|private
name|RadioButton
name|resolveStringsBibTex
decl_stmt|;
DECL|field|stringsResolveToggleGroup
annotation|@
name|FXML
specifier|private
name|ToggleGroup
name|stringsResolveToggleGroup
decl_stmt|;
DECL|field|resolveStringsAll
annotation|@
name|FXML
specifier|private
name|RadioButton
name|resolveStringsAll
decl_stmt|;
DECL|field|resolvStringsExcept
annotation|@
name|FXML
specifier|private
name|TextField
name|resolvStringsExcept
decl_stmt|;
DECL|field|newLineSeparator
annotation|@
name|FXML
specifier|private
name|ComboBox
argument_list|<
name|NewLineSeperator
argument_list|>
name|newLineSeparator
decl_stmt|;
DECL|field|alwaysReformatBib
annotation|@
name|FXML
specifier|private
name|CheckBox
name|alwaysReformatBib
decl_stmt|;
DECL|field|mainFileDir
annotation|@
name|FXML
specifier|private
name|TextField
name|mainFileDir
decl_stmt|;
DECL|field|useBibLocationAsPrimary
annotation|@
name|FXML
specifier|private
name|CheckBox
name|useBibLocationAsPrimary
decl_stmt|;
DECL|field|autolinkRegexHelp
annotation|@
name|FXML
specifier|private
name|Button
name|autolinkRegexHelp
decl_stmt|;
DECL|field|autolinkFilesWithBibtex
annotation|@
name|FXML
specifier|private
name|RadioButton
name|autolinkFilesWithBibtex
decl_stmt|;
DECL|field|autolinkToggleGroup
annotation|@
name|FXML
specifier|private
name|ToggleGroup
name|autolinkToggleGroup
decl_stmt|;
DECL|field|autolinkFilesOnlyBibtex
annotation|@
name|FXML
specifier|private
name|RadioButton
name|autolinkFilesOnlyBibtex
decl_stmt|;
DECL|field|autolinkUseRegex
annotation|@
name|FXML
specifier|private
name|RadioButton
name|autolinkUseRegex
decl_stmt|;
DECL|field|autolinkRegexTerm
annotation|@
name|FXML
specifier|private
name|TextField
name|autolinkRegexTerm
decl_stmt|;
DECL|field|searchFilesOnOpen
annotation|@
name|FXML
specifier|private
name|CheckBox
name|searchFilesOnOpen
decl_stmt|;
DECL|field|openBrowseOnCreate
annotation|@
name|FXML
specifier|private
name|CheckBox
name|openBrowseOnCreate
decl_stmt|;
DECL|field|autosaveLocalLibraries
annotation|@
name|FXML
specifier|private
name|CheckBox
name|autosaveLocalLibraries
decl_stmt|;
DECL|field|autosaveLocalLibrariesHelp
annotation|@
name|FXML
specifier|private
name|Button
name|autosaveLocalLibrariesHelp
decl_stmt|;
DECL|field|dialogService
specifier|private
specifier|final
name|DialogService
name|dialogService
decl_stmt|;
DECL|field|preferences
specifier|private
specifier|final
name|JabRefPreferences
name|preferences
decl_stmt|;
DECL|field|viewModel
specifier|private
name|FileTabViewModel
name|viewModel
decl_stmt|;
DECL|method|FileTabView (DialogService dialogService, JabRefPreferences preferences)
specifier|public
name|FileTabView
parameter_list|(
name|DialogService
name|dialogService
parameter_list|,
name|JabRefPreferences
name|preferences
parameter_list|)
block|{
name|this
operator|.
name|dialogService
operator|=
name|dialogService
expr_stmt|;
name|this
operator|.
name|preferences
operator|=
name|preferences
expr_stmt|;
name|ViewLoader
operator|.
name|view
argument_list|(
name|this
argument_list|)
operator|.
name|root
argument_list|(
name|this
argument_list|)
operator|.
name|load
argument_list|()
expr_stmt|;
block|}
DECL|method|initialize ()
specifier|public
name|void
name|initialize
parameter_list|()
block|{
name|viewModel
operator|=
operator|new
name|FileTabViewModel
argument_list|(
name|dialogService
argument_list|,
name|preferences
argument_list|)
expr_stmt|;
name|ActionFactory
name|actionFactory
init|=
operator|new
name|ActionFactory
argument_list|(
name|Globals
operator|.
name|getKeyPrefs
argument_list|()
argument_list|)
decl_stmt|;
name|actionFactory
operator|.
name|configureIconButton
argument_list|(
name|StandardActions
operator|.
name|HELP_REGEX_SEARCH
argument_list|,
operator|new
name|HelpAction
argument_list|(
name|HelpFile
operator|.
name|REGEX_SEARCH
argument_list|)
argument_list|,
name|autolinkRegexHelp
argument_list|)
expr_stmt|;
name|actionFactory
operator|.
name|configureIconButton
argument_list|(
name|StandardActions
operator|.
name|HELP
argument_list|,
operator|new
name|HelpAction
argument_list|(
name|HelpFile
operator|.
name|AUTOSAVE
argument_list|)
argument_list|,
name|autosaveLocalLibrariesHelp
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
DECL|method|getBuilder ()
specifier|public
name|Node
name|getBuilder
parameter_list|()
block|{
return|return
name|this
return|;
block|}
annotation|@
name|Override
DECL|method|setValues ()
specifier|public
name|void
name|setValues
parameter_list|()
block|{
comment|// Done by bindings
block|}
annotation|@
name|Override
DECL|method|storeSettings ()
specifier|public
name|void
name|storeSettings
parameter_list|()
block|{
name|viewModel
operator|.
name|storeSettings
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Deprecated
annotation|@
name|Override
DECL|method|validateSettings ()
specifier|public
name|boolean
name|validateSettings
parameter_list|()
block|{
return|return
name|viewModel
operator|.
name|validateSettings
argument_list|()
return|;
block|}
annotation|@
name|Override
DECL|method|getTabName ()
specifier|public
name|String
name|getTabName
parameter_list|()
block|{
return|return
name|Localization
operator|.
name|lang
argument_list|(
literal|"File"
argument_list|)
return|;
block|}
DECL|method|mainFileDirBrowse ()
specifier|public
name|void
name|mainFileDirBrowse
parameter_list|()
block|{
name|viewModel
operator|.
name|mainFileDirBrowse
argument_list|()
expr_stmt|;
block|}
block|}
end_class

end_unit

