begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_package
DECL|package|org.jabref.gui.preferences
package|package
name|org
operator|.
name|jabref
operator|.
name|gui
operator|.
name|preferences
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Collections
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Locale
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Objects
import|;
end_import

begin_import
import|import
name|javafx
operator|.
name|collections
operator|.
name|FXCollections
import|;
end_import

begin_import
import|import
name|javafx
operator|.
name|scene
operator|.
name|Node
import|;
end_import

begin_import
import|import
name|javafx
operator|.
name|scene
operator|.
name|control
operator|.
name|CheckBox
import|;
end_import

begin_import
import|import
name|javafx
operator|.
name|scene
operator|.
name|control
operator|.
name|ComboBox
import|;
end_import

begin_import
import|import
name|javafx
operator|.
name|scene
operator|.
name|control
operator|.
name|Label
import|;
end_import

begin_import
import|import
name|javafx
operator|.
name|scene
operator|.
name|control
operator|.
name|RadioButton
import|;
end_import

begin_import
import|import
name|javafx
operator|.
name|scene
operator|.
name|control
operator|.
name|TextField
import|;
end_import

begin_import
import|import
name|javafx
operator|.
name|scene
operator|.
name|layout
operator|.
name|GridPane
import|;
end_import

begin_import
import|import
name|javafx
operator|.
name|scene
operator|.
name|layout
operator|.
name|Pane
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|Globals
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|logic
operator|.
name|l10n
operator|.
name|Localization
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|model
operator|.
name|entry
operator|.
name|BibEntry
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|model
operator|.
name|entry
operator|.
name|InternalBibtexFields
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|preferences
operator|.
name|JabRefPreferences
import|;
end_import

begin_class
DECL|class|TablePrefsTab
class|class
name|TablePrefsTab
extends|extends
name|Pane
implements|implements
name|PrefsTab
block|{
DECL|field|prefs
specifier|private
specifier|final
name|JabRefPreferences
name|prefs
decl_stmt|;
DECL|field|autoResizeMode
specifier|private
specifier|final
name|CheckBox
name|autoResizeMode
decl_stmt|;
DECL|field|priDesc
specifier|private
specifier|final
name|CheckBox
name|priDesc
decl_stmt|;
DECL|field|secDesc
specifier|private
specifier|final
name|CheckBox
name|secDesc
decl_stmt|;
DECL|field|terDesc
specifier|private
specifier|final
name|CheckBox
name|terDesc
decl_stmt|;
DECL|field|namesAsIs
specifier|private
specifier|final
name|RadioButton
name|namesAsIs
decl_stmt|;
DECL|field|namesFf
specifier|private
specifier|final
name|RadioButton
name|namesFf
decl_stmt|;
DECL|field|namesFl
specifier|private
specifier|final
name|RadioButton
name|namesFl
decl_stmt|;
DECL|field|namesNatbib
specifier|private
specifier|final
name|RadioButton
name|namesNatbib
decl_stmt|;
DECL|field|abbrNames
specifier|private
specifier|final
name|RadioButton
name|abbrNames
decl_stmt|;
DECL|field|noAbbrNames
specifier|private
specifier|final
name|RadioButton
name|noAbbrNames
decl_stmt|;
DECL|field|lastNamesOnly
specifier|private
specifier|final
name|RadioButton
name|lastNamesOnly
decl_stmt|;
DECL|field|priField
specifier|private
specifier|final
name|TextField
name|priField
decl_stmt|;
DECL|field|secField
specifier|private
specifier|final
name|TextField
name|secField
decl_stmt|;
DECL|field|terField
specifier|private
specifier|final
name|TextField
name|terField
decl_stmt|;
DECL|field|numericFields
specifier|private
specifier|final
name|TextField
name|numericFields
decl_stmt|;
DECL|field|priSort
specifier|private
specifier|final
name|ComboBox
name|priSort
decl_stmt|;
DECL|field|secSort
specifier|private
specifier|final
name|ComboBox
name|secSort
decl_stmt|;
DECL|field|terSort
specifier|private
specifier|final
name|ComboBox
name|terSort
decl_stmt|;
DECL|field|builder
specifier|private
specifier|final
name|GridPane
name|builder
init|=
operator|new
name|GridPane
argument_list|()
decl_stmt|;
comment|/**      * Customization of external program paths.      *      * @param prefs      *            a<code>JabRefPreferences</code> value      */
DECL|method|TablePrefsTab (JabRefPreferences prefs)
specifier|public
name|TablePrefsTab
parameter_list|(
name|JabRefPreferences
name|prefs
parameter_list|)
block|{
name|this
operator|.
name|prefs
operator|=
name|prefs
expr_stmt|;
comment|/**          * Added Bibtexkey to combobox.          *          * [ 1540646 ] default sort order: bibtexkey          *          * http://sourceforge.net/tracker/index.php?func=detail&aid=1540646&group_id=92314&atid=600306          */
name|List
argument_list|<
name|String
argument_list|>
name|fieldNames
init|=
name|InternalBibtexFields
operator|.
name|getAllPublicFieldNames
argument_list|()
decl_stmt|;
name|fieldNames
operator|.
name|add
argument_list|(
name|BibEntry
operator|.
name|KEY_FIELD
argument_list|)
expr_stmt|;
name|Collections
operator|.
name|sort
argument_list|(
name|fieldNames
argument_list|)
expr_stmt|;
name|String
index|[]
name|allPlusKey
init|=
name|fieldNames
operator|.
name|toArray
argument_list|(
operator|new
name|String
index|[
name|fieldNames
operator|.
name|size
argument_list|()
index|]
argument_list|)
decl_stmt|;
name|priSort
operator|=
operator|new
name|ComboBox
argument_list|<>
argument_list|(
name|FXCollections
operator|.
name|observableArrayList
argument_list|(
name|allPlusKey
argument_list|)
argument_list|)
expr_stmt|;
name|secSort
operator|=
operator|new
name|ComboBox
argument_list|<>
argument_list|(
name|FXCollections
operator|.
name|observableArrayList
argument_list|(
name|allPlusKey
argument_list|)
argument_list|)
expr_stmt|;
name|terSort
operator|=
operator|new
name|ComboBox
argument_list|<>
argument_list|(
name|FXCollections
operator|.
name|observableArrayList
argument_list|(
name|allPlusKey
argument_list|)
argument_list|)
expr_stmt|;
name|autoResizeMode
operator|=
operator|new
name|CheckBox
argument_list|(
name|Localization
operator|.
name|lang
argument_list|(
literal|"Fit table horizontally on screen"
argument_list|)
argument_list|)
expr_stmt|;
name|autoResizeMode
operator|.
name|setFont
argument_list|(
name|FontSize
operator|.
name|smallFont
argument_list|)
expr_stmt|;
name|namesAsIs
operator|=
operator|new
name|RadioButton
argument_list|(
name|Localization
operator|.
name|lang
argument_list|(
literal|"Show names unchanged"
argument_list|)
argument_list|)
expr_stmt|;
name|namesAsIs
operator|.
name|setFont
argument_list|(
name|FontSize
operator|.
name|smallFont
argument_list|)
expr_stmt|;
name|namesFf
operator|=
operator|new
name|RadioButton
argument_list|(
name|Localization
operator|.
name|lang
argument_list|(
literal|"Show 'Firstname Lastname'"
argument_list|)
argument_list|)
expr_stmt|;
name|namesFf
operator|.
name|setFont
argument_list|(
name|FontSize
operator|.
name|smallFont
argument_list|)
expr_stmt|;
name|namesFl
operator|=
operator|new
name|RadioButton
argument_list|(
name|Localization
operator|.
name|lang
argument_list|(
literal|"Show 'Lastname, Firstname'"
argument_list|)
argument_list|)
expr_stmt|;
name|namesFl
operator|.
name|setFont
argument_list|(
name|FontSize
operator|.
name|smallFont
argument_list|)
expr_stmt|;
name|namesNatbib
operator|=
operator|new
name|RadioButton
argument_list|(
name|Localization
operator|.
name|lang
argument_list|(
literal|"Natbib style"
argument_list|)
argument_list|)
expr_stmt|;
name|namesNatbib
operator|.
name|setFont
argument_list|(
name|FontSize
operator|.
name|smallFont
argument_list|)
expr_stmt|;
name|noAbbrNames
operator|=
operator|new
name|RadioButton
argument_list|(
name|Localization
operator|.
name|lang
argument_list|(
literal|"Do not abbreviate names"
argument_list|)
argument_list|)
expr_stmt|;
name|noAbbrNames
operator|.
name|setFont
argument_list|(
name|FontSize
operator|.
name|smallFont
argument_list|)
expr_stmt|;
name|abbrNames
operator|=
operator|new
name|RadioButton
argument_list|(
name|Localization
operator|.
name|lang
argument_list|(
literal|"Abbreviate names"
argument_list|)
argument_list|)
expr_stmt|;
name|abbrNames
operator|.
name|setFont
argument_list|(
name|FontSize
operator|.
name|smallFont
argument_list|)
expr_stmt|;
name|lastNamesOnly
operator|=
operator|new
name|RadioButton
argument_list|(
name|Localization
operator|.
name|lang
argument_list|(
literal|"Show last names only"
argument_list|)
argument_list|)
expr_stmt|;
name|lastNamesOnly
operator|.
name|setFont
argument_list|(
name|FontSize
operator|.
name|smallFont
argument_list|)
expr_stmt|;
name|priField
operator|=
operator|new
name|TextField
argument_list|()
expr_stmt|;
name|secField
operator|=
operator|new
name|TextField
argument_list|()
expr_stmt|;
name|terField
operator|=
operator|new
name|TextField
argument_list|()
expr_stmt|;
name|numericFields
operator|=
operator|new
name|TextField
argument_list|()
expr_stmt|;
name|priSort
operator|.
name|setValue
argument_list|(
name|Localization
operator|.
name|lang
argument_list|(
literal|"<select>"
argument_list|)
argument_list|)
expr_stmt|;
name|secSort
operator|.
name|setValue
argument_list|(
name|Localization
operator|.
name|lang
argument_list|(
literal|"<select>"
argument_list|)
argument_list|)
expr_stmt|;
name|terSort
operator|.
name|setValue
argument_list|(
name|Localization
operator|.
name|lang
argument_list|(
literal|"<select>"
argument_list|)
argument_list|)
expr_stmt|;
name|priSort
operator|.
name|setOnAction
argument_list|(
name|e
lambda|->
block|{
if|if
condition|(
name|priSort
operator|.
name|getBaselineOffset
argument_list|()
operator|>
literal|0
condition|)
block|{
name|priField
operator|.
name|setText
argument_list|(
name|priSort
operator|.
name|getItems
argument_list|()
operator|.
name|toString
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
argument_list|)
expr_stmt|;
name|secSort
operator|.
name|setOnAction
argument_list|(
name|e
lambda|->
block|{
if|if
condition|(
name|secSort
operator|.
name|getBaselineOffset
argument_list|()
operator|>
literal|0
condition|)
block|{
name|secField
operator|.
name|setText
argument_list|(
name|secSort
operator|.
name|getItems
argument_list|()
operator|.
name|toString
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
argument_list|)
expr_stmt|;
name|terSort
operator|.
name|setOnAction
argument_list|(
name|e
lambda|->
block|{
if|if
condition|(
name|terSort
operator|.
name|getBaselineOffset
argument_list|()
operator|>
literal|0
condition|)
block|{
name|terField
operator|.
name|setText
argument_list|(
name|terSort
operator|.
name|getItems
argument_list|()
operator|.
name|toString
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
argument_list|)
expr_stmt|;
name|priDesc
operator|=
operator|new
name|CheckBox
argument_list|(
name|Localization
operator|.
name|lang
argument_list|(
literal|"Descending"
argument_list|)
argument_list|)
expr_stmt|;
name|priDesc
operator|.
name|setFont
argument_list|(
name|FontSize
operator|.
name|smallFont
argument_list|)
expr_stmt|;
name|secDesc
operator|=
operator|new
name|CheckBox
argument_list|(
name|Localization
operator|.
name|lang
argument_list|(
literal|"Descending"
argument_list|)
argument_list|)
expr_stmt|;
name|secDesc
operator|.
name|setFont
argument_list|(
name|FontSize
operator|.
name|smallFont
argument_list|)
expr_stmt|;
name|terDesc
operator|=
operator|new
name|CheckBox
argument_list|(
name|Localization
operator|.
name|lang
argument_list|(
literal|"Descending"
argument_list|)
argument_list|)
expr_stmt|;
name|terDesc
operator|.
name|setFont
argument_list|(
name|FontSize
operator|.
name|smallFont
argument_list|)
expr_stmt|;
name|Label
name|formatOfAuthor
init|=
operator|new
name|Label
argument_list|(
name|Localization
operator|.
name|lang
argument_list|(
literal|"Format of author and editor names"
argument_list|)
operator|+
literal|"  ----------------------"
argument_list|)
decl_stmt|;
name|formatOfAuthor
operator|.
name|setFont
argument_list|(
name|FontSize
operator|.
name|bigFont
argument_list|)
expr_stmt|;
name|builder
operator|.
name|add
argument_list|(
name|formatOfAuthor
argument_list|,
literal|1
argument_list|,
literal|1
argument_list|)
expr_stmt|;
name|builder
operator|.
name|add
argument_list|(
name|namesAsIs
argument_list|,
literal|1
argument_list|,
literal|2
argument_list|)
expr_stmt|;
name|builder
operator|.
name|add
argument_list|(
name|noAbbrNames
argument_list|,
literal|2
argument_list|,
literal|2
argument_list|)
expr_stmt|;
name|builder
operator|.
name|add
argument_list|(
name|namesFf
argument_list|,
literal|1
argument_list|,
literal|3
argument_list|)
expr_stmt|;
name|builder
operator|.
name|add
argument_list|(
name|abbrNames
argument_list|,
literal|2
argument_list|,
literal|3
argument_list|)
expr_stmt|;
name|builder
operator|.
name|add
argument_list|(
name|namesFl
argument_list|,
literal|1
argument_list|,
literal|4
argument_list|)
expr_stmt|;
name|builder
operator|.
name|add
argument_list|(
name|lastNamesOnly
argument_list|,
literal|2
argument_list|,
literal|4
argument_list|)
expr_stmt|;
name|builder
operator|.
name|add
argument_list|(
name|namesNatbib
argument_list|,
literal|1
argument_list|,
literal|5
argument_list|)
expr_stmt|;
name|Label
name|label1
init|=
operator|new
name|Label
argument_list|(
literal|""
argument_list|)
decl_stmt|;
name|builder
operator|.
name|add
argument_list|(
name|label1
argument_list|,
literal|1
argument_list|,
literal|6
argument_list|)
expr_stmt|;
name|Label
name|defaultSortCriteria
init|=
operator|new
name|Label
argument_list|(
name|Localization
operator|.
name|lang
argument_list|(
literal|"Default sort criteria"
argument_list|)
operator|+
literal|"  ----------------------------------------"
argument_list|)
decl_stmt|;
name|defaultSortCriteria
operator|.
name|setFont
argument_list|(
name|FontSize
operator|.
name|bigFont
argument_list|)
expr_stmt|;
name|builder
operator|.
name|add
argument_list|(
name|defaultSortCriteria
argument_list|,
literal|1
argument_list|,
literal|7
argument_list|)
expr_stmt|;
comment|// Create a new panel with its own FormLayout for these items:
name|Label
name|primarySortCriterion
init|=
operator|new
name|Label
argument_list|(
name|Localization
operator|.
name|lang
argument_list|(
literal|"Primary sort criterion"
argument_list|)
argument_list|)
decl_stmt|;
name|primarySortCriterion
operator|.
name|setFont
argument_list|(
name|FontSize
operator|.
name|smallFont
argument_list|)
expr_stmt|;
name|builder
operator|.
name|add
argument_list|(
name|primarySortCriterion
argument_list|,
literal|1
argument_list|,
literal|8
argument_list|)
expr_stmt|;
name|builder
operator|.
name|add
argument_list|(
name|priSort
argument_list|,
literal|2
argument_list|,
literal|8
argument_list|)
expr_stmt|;
name|builder
operator|.
name|add
argument_list|(
name|priField
argument_list|,
literal|3
argument_list|,
literal|8
argument_list|)
expr_stmt|;
name|builder
operator|.
name|add
argument_list|(
name|priDesc
argument_list|,
literal|4
argument_list|,
literal|8
argument_list|)
expr_stmt|;
name|Label
name|secondarySortCriterion
init|=
operator|new
name|Label
argument_list|(
name|Localization
operator|.
name|lang
argument_list|(
literal|"Secondary sort criterion"
argument_list|)
argument_list|)
decl_stmt|;
name|secondarySortCriterion
operator|.
name|setFont
argument_list|(
name|FontSize
operator|.
name|smallFont
argument_list|)
expr_stmt|;
name|builder
operator|.
name|add
argument_list|(
name|secondarySortCriterion
argument_list|,
literal|1
argument_list|,
literal|9
argument_list|)
expr_stmt|;
name|builder
operator|.
name|add
argument_list|(
name|secSort
argument_list|,
literal|2
argument_list|,
literal|9
argument_list|)
expr_stmt|;
name|builder
operator|.
name|add
argument_list|(
name|secField
argument_list|,
literal|3
argument_list|,
literal|9
argument_list|)
expr_stmt|;
name|builder
operator|.
name|add
argument_list|(
name|secDesc
argument_list|,
literal|4
argument_list|,
literal|9
argument_list|)
expr_stmt|;
name|Label
name|tertiarySortCriterion
init|=
operator|new
name|Label
argument_list|(
name|Localization
operator|.
name|lang
argument_list|(
literal|"Tertiary sort criterion"
argument_list|)
argument_list|)
decl_stmt|;
name|tertiarySortCriterion
operator|.
name|setFont
argument_list|(
name|FontSize
operator|.
name|smallFont
argument_list|)
expr_stmt|;
name|builder
operator|.
name|add
argument_list|(
name|tertiarySortCriterion
argument_list|,
literal|1
argument_list|,
literal|10
argument_list|)
expr_stmt|;
name|builder
operator|.
name|add
argument_list|(
name|terSort
argument_list|,
literal|2
argument_list|,
literal|10
argument_list|)
expr_stmt|;
name|builder
operator|.
name|add
argument_list|(
name|terField
argument_list|,
literal|3
argument_list|,
literal|10
argument_list|)
expr_stmt|;
name|builder
operator|.
name|add
argument_list|(
name|terDesc
argument_list|,
literal|4
argument_list|,
literal|10
argument_list|)
expr_stmt|;
name|Label
name|sortFields
init|=
operator|new
name|Label
argument_list|(
name|Localization
operator|.
name|lang
argument_list|(
literal|"Sort the following fields as numeric fields"
argument_list|)
operator|+
literal|':'
argument_list|)
decl_stmt|;
name|sortFields
operator|.
name|setFont
argument_list|(
name|FontSize
operator|.
name|smallFont
argument_list|)
expr_stmt|;
name|builder
operator|.
name|add
argument_list|(
name|sortFields
argument_list|,
literal|1
argument_list|,
literal|11
argument_list|)
expr_stmt|;
name|builder
operator|.
name|add
argument_list|(
name|numericFields
argument_list|,
literal|2
argument_list|,
literal|11
argument_list|)
expr_stmt|;
name|builder
operator|.
name|add
argument_list|(
operator|new
name|Label
argument_list|(
literal|""
argument_list|)
argument_list|,
literal|1
argument_list|,
literal|12
argument_list|)
expr_stmt|;
name|Label
name|general
init|=
operator|new
name|Label
argument_list|(
name|Localization
operator|.
name|lang
argument_list|(
literal|"General"
argument_list|)
operator|+
literal|" ------------------------------------------------------"
argument_list|)
decl_stmt|;
name|general
operator|.
name|setFont
argument_list|(
name|FontSize
operator|.
name|bigFont
argument_list|)
expr_stmt|;
name|builder
operator|.
name|add
argument_list|(
name|general
argument_list|,
literal|1
argument_list|,
literal|13
argument_list|)
expr_stmt|;
name|builder
operator|.
name|add
argument_list|(
name|autoResizeMode
argument_list|,
literal|1
argument_list|,
literal|14
argument_list|)
expr_stmt|;
name|namesNatbib
operator|.
name|setOnAction
argument_list|(
name|e
lambda|->
block|{
name|abbrNames
operator|.
name|setDisable
argument_list|(
name|namesNatbib
operator|.
name|isSelected
argument_list|()
argument_list|)
expr_stmt|;
name|lastNamesOnly
operator|.
name|setDisable
argument_list|(
name|namesNatbib
operator|.
name|isSelected
argument_list|()
argument_list|)
expr_stmt|;
name|noAbbrNames
operator|.
name|setDisable
argument_list|(
name|namesNatbib
operator|.
name|isSelected
argument_list|()
argument_list|)
expr_stmt|;
block|}
argument_list|)
expr_stmt|;
block|}
DECL|method|getBuilder ()
specifier|public
name|Node
name|getBuilder
parameter_list|()
block|{
return|return
name|builder
return|;
block|}
annotation|@
name|Override
DECL|method|setValues ()
specifier|public
name|void
name|setValues
parameter_list|()
block|{
name|autoResizeMode
operator|.
name|setSelected
argument_list|(
name|prefs
operator|.
name|getBoolean
argument_list|(
name|JabRefPreferences
operator|.
name|AUTO_RESIZE_MODE
argument_list|)
argument_list|)
expr_stmt|;
name|priField
operator|.
name|setText
argument_list|(
name|prefs
operator|.
name|get
argument_list|(
name|JabRefPreferences
operator|.
name|TABLE_PRIMARY_SORT_FIELD
argument_list|)
argument_list|)
expr_stmt|;
name|secField
operator|.
name|setText
argument_list|(
name|prefs
operator|.
name|get
argument_list|(
name|JabRefPreferences
operator|.
name|TABLE_SECONDARY_SORT_FIELD
argument_list|)
argument_list|)
expr_stmt|;
name|terField
operator|.
name|setText
argument_list|(
name|prefs
operator|.
name|get
argument_list|(
name|JabRefPreferences
operator|.
name|TABLE_TERTIARY_SORT_FIELD
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|prefs
operator|.
name|getBoolean
argument_list|(
name|JabRefPreferences
operator|.
name|NAMES_AS_IS
argument_list|)
condition|)
block|{
name|namesAsIs
operator|.
name|setSelected
argument_list|(
literal|true
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|prefs
operator|.
name|getBoolean
argument_list|(
name|JabRefPreferences
operator|.
name|NAMES_FIRST_LAST
argument_list|)
condition|)
block|{
name|namesFf
operator|.
name|setSelected
argument_list|(
literal|true
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|prefs
operator|.
name|getBoolean
argument_list|(
name|JabRefPreferences
operator|.
name|NAMES_NATBIB
argument_list|)
condition|)
block|{
name|namesNatbib
operator|.
name|setSelected
argument_list|(
literal|true
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|namesFl
operator|.
name|setSelected
argument_list|(
literal|true
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|prefs
operator|.
name|getBoolean
argument_list|(
name|JabRefPreferences
operator|.
name|ABBR_AUTHOR_NAMES
argument_list|)
condition|)
block|{
name|abbrNames
operator|.
name|setSelected
argument_list|(
literal|true
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|prefs
operator|.
name|getBoolean
argument_list|(
name|JabRefPreferences
operator|.
name|NAMES_LAST_ONLY
argument_list|)
condition|)
block|{
name|lastNamesOnly
operator|.
name|setSelected
argument_list|(
literal|true
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|noAbbrNames
operator|.
name|setSelected
argument_list|(
literal|true
argument_list|)
expr_stmt|;
block|}
name|priDesc
operator|.
name|setSelected
argument_list|(
name|prefs
operator|.
name|getBoolean
argument_list|(
name|JabRefPreferences
operator|.
name|TABLE_PRIMARY_SORT_DESCENDING
argument_list|)
argument_list|)
expr_stmt|;
name|secDesc
operator|.
name|setSelected
argument_list|(
name|prefs
operator|.
name|getBoolean
argument_list|(
name|JabRefPreferences
operator|.
name|TABLE_SECONDARY_SORT_DESCENDING
argument_list|)
argument_list|)
expr_stmt|;
name|terDesc
operator|.
name|setSelected
argument_list|(
name|prefs
operator|.
name|getBoolean
argument_list|(
name|JabRefPreferences
operator|.
name|TABLE_TERTIARY_SORT_DESCENDING
argument_list|)
argument_list|)
expr_stmt|;
name|abbrNames
operator|.
name|setDisable
argument_list|(
name|namesNatbib
operator|.
name|isSelected
argument_list|()
argument_list|)
expr_stmt|;
name|lastNamesOnly
operator|.
name|setDisable
argument_list|(
name|namesNatbib
operator|.
name|isSelected
argument_list|()
argument_list|)
expr_stmt|;
name|noAbbrNames
operator|.
name|setDisable
argument_list|(
name|namesNatbib
operator|.
name|isSelected
argument_list|()
argument_list|)
expr_stmt|;
name|String
name|numF
init|=
name|prefs
operator|.
name|get
argument_list|(
name|JabRefPreferences
operator|.
name|NUMERIC_FIELDS
argument_list|)
decl_stmt|;
if|if
condition|(
name|numF
operator|==
literal|null
condition|)
block|{
name|numericFields
operator|.
name|setText
argument_list|(
literal|""
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|numericFields
operator|.
name|setText
argument_list|(
name|numF
argument_list|)
expr_stmt|;
block|}
block|}
comment|/**      * Store changes to table preferences. This method is called when the user      * clicks Ok.      *      */
annotation|@
name|Override
DECL|method|storeSettings ()
specifier|public
name|void
name|storeSettings
parameter_list|()
block|{
name|prefs
operator|.
name|putBoolean
argument_list|(
name|JabRefPreferences
operator|.
name|NAMES_AS_IS
argument_list|,
name|namesAsIs
operator|.
name|isSelected
argument_list|()
argument_list|)
expr_stmt|;
name|prefs
operator|.
name|putBoolean
argument_list|(
name|JabRefPreferences
operator|.
name|NAMES_FIRST_LAST
argument_list|,
name|namesFf
operator|.
name|isSelected
argument_list|()
argument_list|)
expr_stmt|;
name|prefs
operator|.
name|putBoolean
argument_list|(
name|JabRefPreferences
operator|.
name|NAMES_NATBIB
argument_list|,
name|namesNatbib
operator|.
name|isSelected
argument_list|()
argument_list|)
expr_stmt|;
name|prefs
operator|.
name|putBoolean
argument_list|(
name|JabRefPreferences
operator|.
name|NAMES_LAST_ONLY
argument_list|,
name|lastNamesOnly
operator|.
name|isSelected
argument_list|()
argument_list|)
expr_stmt|;
name|prefs
operator|.
name|putBoolean
argument_list|(
name|JabRefPreferences
operator|.
name|ABBR_AUTHOR_NAMES
argument_list|,
name|abbrNames
operator|.
name|isSelected
argument_list|()
argument_list|)
expr_stmt|;
name|prefs
operator|.
name|putBoolean
argument_list|(
name|JabRefPreferences
operator|.
name|AUTO_RESIZE_MODE
argument_list|,
name|autoResizeMode
operator|.
name|isSelected
argument_list|()
argument_list|)
expr_stmt|;
name|prefs
operator|.
name|putBoolean
argument_list|(
name|JabRefPreferences
operator|.
name|TABLE_PRIMARY_SORT_DESCENDING
argument_list|,
name|priDesc
operator|.
name|isSelected
argument_list|()
argument_list|)
expr_stmt|;
name|prefs
operator|.
name|putBoolean
argument_list|(
name|JabRefPreferences
operator|.
name|TABLE_SECONDARY_SORT_DESCENDING
argument_list|,
name|secDesc
operator|.
name|isSelected
argument_list|()
argument_list|)
expr_stmt|;
name|prefs
operator|.
name|putBoolean
argument_list|(
name|JabRefPreferences
operator|.
name|TABLE_TERTIARY_SORT_DESCENDING
argument_list|,
name|terDesc
operator|.
name|isSelected
argument_list|()
argument_list|)
expr_stmt|;
name|prefs
operator|.
name|put
argument_list|(
name|JabRefPreferences
operator|.
name|TABLE_PRIMARY_SORT_FIELD
argument_list|,
name|priField
operator|.
name|getText
argument_list|()
operator|.
name|toLowerCase
argument_list|(
name|Locale
operator|.
name|ROOT
argument_list|)
operator|.
name|trim
argument_list|()
argument_list|)
expr_stmt|;
name|prefs
operator|.
name|put
argument_list|(
name|JabRefPreferences
operator|.
name|TABLE_SECONDARY_SORT_FIELD
argument_list|,
name|secField
operator|.
name|getText
argument_list|()
operator|.
name|toLowerCase
argument_list|(
name|Locale
operator|.
name|ROOT
argument_list|)
operator|.
name|trim
argument_list|()
argument_list|)
expr_stmt|;
name|prefs
operator|.
name|put
argument_list|(
name|JabRefPreferences
operator|.
name|TABLE_TERTIARY_SORT_FIELD
argument_list|,
name|terField
operator|.
name|getText
argument_list|()
operator|.
name|toLowerCase
argument_list|(
name|Locale
operator|.
name|ROOT
argument_list|)
operator|.
name|trim
argument_list|()
argument_list|)
expr_stmt|;
name|String
name|oldVal
init|=
name|prefs
operator|.
name|get
argument_list|(
name|JabRefPreferences
operator|.
name|NUMERIC_FIELDS
argument_list|)
decl_stmt|;
name|String
name|newVal
init|=
name|numericFields
operator|.
name|getText
argument_list|()
operator|.
name|trim
argument_list|()
decl_stmt|;
if|if
condition|(
name|newVal
operator|.
name|isEmpty
argument_list|()
condition|)
block|{
name|newVal
operator|=
literal|null
expr_stmt|;
block|}
if|if
condition|(
operator|!
name|Objects
operator|.
name|equals
argument_list|(
name|oldVal
argument_list|,
name|newVal
argument_list|)
condition|)
block|{
name|prefs
operator|.
name|put
argument_list|(
name|JabRefPreferences
operator|.
name|NUMERIC_FIELDS
argument_list|,
name|newVal
argument_list|)
expr_stmt|;
name|InternalBibtexFields
operator|.
name|setNumericFields
argument_list|(
name|Globals
operator|.
name|prefs
operator|.
name|getStringList
argument_list|(
name|JabRefPreferences
operator|.
name|NUMERIC_FIELDS
argument_list|)
argument_list|)
expr_stmt|;
block|}
block|}
annotation|@
name|Override
DECL|method|validateSettings ()
specifier|public
name|boolean
name|validateSettings
parameter_list|()
block|{
return|return
literal|true
return|;
block|}
annotation|@
name|Override
DECL|method|getTabName ()
specifier|public
name|String
name|getTabName
parameter_list|()
block|{
return|return
name|Localization
operator|.
name|lang
argument_list|(
literal|"Entry table"
argument_list|)
return|;
block|}
block|}
end_class

end_unit

