begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_package
DECL|package|org.jabref.logic.bibtex.comparator
package|package
name|org
operator|.
name|jabref
operator|.
name|logic
operator|.
name|bibtex
operator|.
name|comparator
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Collections
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Optional
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|model
operator|.
name|database
operator|.
name|BibDatabaseContext
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Test
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|junit
operator|.
name|Assert
operator|.
name|assertEquals
import|;
end_import

begin_class
DECL|class|BibDatabaseDiffTest
specifier|public
class|class
name|BibDatabaseDiffTest
block|{
annotation|@
name|Test
DECL|method|compareOfEmptyDatabasesReportsNoDifferences ()
specifier|public
name|void
name|compareOfEmptyDatabasesReportsNoDifferences
parameter_list|()
throws|throws
name|Exception
block|{
name|BibDatabaseDiff
name|diff
init|=
name|BibDatabaseDiff
operator|.
name|compare
argument_list|(
operator|new
name|BibDatabaseContext
argument_list|()
argument_list|,
operator|new
name|BibDatabaseContext
argument_list|()
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
name|Optional
operator|.
name|empty
argument_list|()
argument_list|,
name|diff
operator|.
name|getPreambleDifferences
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
name|Optional
operator|.
name|empty
argument_list|()
argument_list|,
name|diff
operator|.
name|getMetaDataDifferences
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
name|Collections
operator|.
name|emptyList
argument_list|()
argument_list|,
name|diff
operator|.
name|getBibStringDifferences
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
name|Collections
operator|.
name|emptyList
argument_list|()
argument_list|,
name|diff
operator|.
name|getEntryDifferences
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

