begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_package
DECL|package|org.jabref.gui.fieldeditors
package|package
name|org
operator|.
name|jabref
operator|.
name|gui
operator|.
name|fieldeditors
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Optional
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|gui
operator|.
name|autocompleter
operator|.
name|AutoCompleteSuggestionProvider
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|logic
operator|.
name|integrity
operator|.
name|FieldCheckers
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|logic
operator|.
name|journals
operator|.
name|JournalAbbreviationLoader
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|logic
operator|.
name|journals
operator|.
name|JournalAbbreviationPreferences
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|logic
operator|.
name|journals
operator|.
name|JournalAbbreviationRepository
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|model
operator|.
name|strings
operator|.
name|StringUtil
import|;
end_import

begin_class
DECL|class|JournalEditorViewModel
specifier|public
class|class
name|JournalEditorViewModel
extends|extends
name|AbstractEditorViewModel
block|{
DECL|field|journalAbbreviationLoader
specifier|private
specifier|final
name|JournalAbbreviationLoader
name|journalAbbreviationLoader
decl_stmt|;
DECL|field|journalAbbreviationPreferences
specifier|private
specifier|final
name|JournalAbbreviationPreferences
name|journalAbbreviationPreferences
decl_stmt|;
DECL|method|JournalEditorViewModel (String fieldName, AutoCompleteSuggestionProvider<?> suggestionProvider, JournalAbbreviationLoader journalAbbreviationLoader, JournalAbbreviationPreferences journalAbbreviationPreferences, FieldCheckers fieldCheckers)
specifier|public
name|JournalEditorViewModel
parameter_list|(
name|String
name|fieldName
parameter_list|,
name|AutoCompleteSuggestionProvider
argument_list|<
name|?
argument_list|>
name|suggestionProvider
parameter_list|,
name|JournalAbbreviationLoader
name|journalAbbreviationLoader
parameter_list|,
name|JournalAbbreviationPreferences
name|journalAbbreviationPreferences
parameter_list|,
name|FieldCheckers
name|fieldCheckers
parameter_list|)
block|{
name|super
argument_list|(
name|fieldName
argument_list|,
name|suggestionProvider
argument_list|,
name|fieldCheckers
argument_list|)
expr_stmt|;
name|this
operator|.
name|journalAbbreviationLoader
operator|=
name|journalAbbreviationLoader
expr_stmt|;
name|this
operator|.
name|journalAbbreviationPreferences
operator|=
name|journalAbbreviationPreferences
expr_stmt|;
block|}
DECL|method|toggleAbbreviation ()
specifier|public
name|void
name|toggleAbbreviation
parameter_list|()
block|{
if|if
condition|(
name|StringUtil
operator|.
name|isBlank
argument_list|(
name|text
operator|.
name|get
argument_list|()
argument_list|)
condition|)
block|{
return|return;
block|}
name|JournalAbbreviationRepository
name|abbreviationRepository
init|=
name|journalAbbreviationLoader
operator|.
name|getRepository
argument_list|(
name|journalAbbreviationPreferences
argument_list|)
decl_stmt|;
if|if
condition|(
name|abbreviationRepository
operator|.
name|isKnownName
argument_list|(
name|text
operator|.
name|get
argument_list|()
argument_list|)
condition|)
block|{
name|Optional
argument_list|<
name|String
argument_list|>
name|nextAbbreviation
init|=
name|abbreviationRepository
operator|.
name|getNextAbbreviation
argument_list|(
name|text
operator|.
name|get
argument_list|()
argument_list|)
decl_stmt|;
if|if
condition|(
name|nextAbbreviation
operator|.
name|isPresent
argument_list|()
condition|)
block|{
name|text
operator|.
name|set
argument_list|(
name|nextAbbreviation
operator|.
name|get
argument_list|()
argument_list|)
expr_stmt|;
comment|// TODO: Add undo
comment|//panel.getUndoManager().addEdit(new UndoableFieldChange(entry, editor.getFieldName(), text, nextAbbreviation));
block|}
block|}
block|}
block|}
end_class

end_unit

