begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_package
DECL|package|org.jabref.gui.fieldeditors
package|package
name|org
operator|.
name|jabref
operator|.
name|gui
operator|.
name|fieldeditors
package|;
end_package

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|gui
operator|.
name|autocompleter
operator|.
name|AutoCompleteSuggestionProvider
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|logic
operator|.
name|integrity
operator|.
name|FieldCheckers
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|logic
operator|.
name|l10n
operator|.
name|Localization
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|BiMap
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|HashBiMap
import|;
end_import

begin_class
DECL|class|TypeEditorViewModel
specifier|public
class|class
name|TypeEditorViewModel
extends|extends
name|MapBasedEditorViewModel
argument_list|<
name|String
argument_list|>
block|{
DECL|field|itemMap
specifier|private
name|BiMap
argument_list|<
name|String
argument_list|,
name|String
argument_list|>
name|itemMap
init|=
name|HashBiMap
operator|.
name|create
argument_list|(
literal|8
argument_list|)
decl_stmt|;
DECL|method|TypeEditorViewModel (String fieldName, AutoCompleteSuggestionProvider<?> suggestionProvider, FieldCheckers fieldCheckers)
specifier|public
name|TypeEditorViewModel
parameter_list|(
name|String
name|fieldName
parameter_list|,
name|AutoCompleteSuggestionProvider
argument_list|<
name|?
argument_list|>
name|suggestionProvider
parameter_list|,
name|FieldCheckers
name|fieldCheckers
parameter_list|)
block|{
name|super
argument_list|(
name|fieldName
argument_list|,
name|suggestionProvider
argument_list|,
name|fieldCheckers
argument_list|)
expr_stmt|;
name|itemMap
operator|.
name|put
argument_list|(
literal|"mathesis"
argument_list|,
name|Localization
operator|.
name|lang
argument_list|(
literal|"Master's thesis"
argument_list|)
argument_list|)
expr_stmt|;
name|itemMap
operator|.
name|put
argument_list|(
literal|"phdthesis"
argument_list|,
name|Localization
operator|.
name|lang
argument_list|(
literal|"PhD thesis"
argument_list|)
argument_list|)
expr_stmt|;
name|itemMap
operator|.
name|put
argument_list|(
literal|"candthesis"
argument_list|,
name|Localization
operator|.
name|lang
argument_list|(
literal|"Candidate thesis"
argument_list|)
argument_list|)
expr_stmt|;
name|itemMap
operator|.
name|put
argument_list|(
literal|"techreport"
argument_list|,
name|Localization
operator|.
name|lang
argument_list|(
literal|"Technical report"
argument_list|)
argument_list|)
expr_stmt|;
name|itemMap
operator|.
name|put
argument_list|(
literal|"resreport"
argument_list|,
name|Localization
operator|.
name|lang
argument_list|(
literal|"Research report"
argument_list|)
argument_list|)
expr_stmt|;
name|itemMap
operator|.
name|put
argument_list|(
literal|"software"
argument_list|,
name|Localization
operator|.
name|lang
argument_list|(
literal|"Software"
argument_list|)
argument_list|)
expr_stmt|;
name|itemMap
operator|.
name|put
argument_list|(
literal|"datacd"
argument_list|,
name|Localization
operator|.
name|lang
argument_list|(
literal|"Data CD"
argument_list|)
argument_list|)
expr_stmt|;
name|itemMap
operator|.
name|put
argument_list|(
literal|"audiocd"
argument_list|,
name|Localization
operator|.
name|lang
argument_list|(
literal|"Audio CD"
argument_list|)
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
DECL|method|getItemMap ()
specifier|protected
name|BiMap
argument_list|<
name|String
argument_list|,
name|String
argument_list|>
name|getItemMap
parameter_list|()
block|{
return|return
name|itemMap
return|;
block|}
annotation|@
name|Override
DECL|method|convertToDisplayText (String object)
specifier|public
name|String
name|convertToDisplayText
parameter_list|(
name|String
name|object
parameter_list|)
block|{
return|return
name|object
return|;
block|}
block|}
end_class

end_unit

