begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_package
DECL|package|net.sf.jabref.util
package|package
name|net
operator|.
name|sf
operator|.
name|jabref
operator|.
name|util
package|;
end_package

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Assert
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Test
import|;
end_import

begin_class
DECL|class|GoogleUrlCleanerTest
specifier|public
class|class
name|GoogleUrlCleanerTest
block|{
annotation|@
name|Test
DECL|method|testCleanUrl ()
specifier|public
name|void
name|testCleanUrl
parameter_list|()
throws|throws
name|Exception
block|{
name|Assert
operator|.
name|assertEquals
argument_list|(
literal|"http://dl.acm.org/citation.cfm?id=321811"
argument_list|,
name|GoogleUrlCleaner
operator|.
name|cleanUrl
argument_list|(
literal|"https://www.google.hr/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&ved=0CC0QFjAA&url=http%3A%2F%2Fdl.acm.org%2Fcitation.cfm%3Fid%3D321811&ei=gHDRUa-IKobotQbMy4GAAg&usg=AFQjCNEBJPUimu-bAns6lSLe-kszz4AiGA&sig2=DotF0pIZD8OhjDcSHPlBbQ"
argument_list|)
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertEquals
argument_list|(
literal|"http://dl.acm.org/citation.cfm?id=321811"
argument_list|,
name|GoogleUrlCleaner
operator|.
name|cleanUrl
argument_list|(
literal|"http://dl.acm.org/citation.cfm?id=321811"
argument_list|)
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertEquals
argument_list|(
literal|"test text"
argument_list|,
name|GoogleUrlCleaner
operator|.
name|cleanUrl
argument_list|(
literal|"test text"
argument_list|)
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertEquals
argument_list|(
literal|" "
argument_list|,
name|GoogleUrlCleaner
operator|.
name|cleanUrl
argument_list|(
literal|" "
argument_list|)
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertEquals
argument_list|(
literal|""
argument_list|,
name|GoogleUrlCleaner
operator|.
name|cleanUrl
argument_list|(
literal|""
argument_list|)
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertEquals
argument_list|(
literal|null
argument_list|,
name|GoogleUrlCleaner
operator|.
name|cleanUrl
argument_list|(
literal|null
argument_list|)
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

