begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_package
DECL|package|net.sf.jabref.logic.util.io
package|package
name|net
operator|.
name|sf
operator|.
name|jabref
operator|.
name|logic
operator|.
name|util
operator|.
name|io
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|File
import|;
end_import

begin_class
DECL|class|AutoSaveUtil
specifier|public
class|class
name|AutoSaveUtil
block|{
comment|/**      * Get a File object pointing to the autosave file corresponding to the given file.      * @param f The database file.      * @return its corresponding autosave file.      */
DECL|method|getAutoSaveFile (File f)
specifier|public
specifier|static
name|File
name|getAutoSaveFile
parameter_list|(
name|File
name|f
parameter_list|)
block|{
return|return
operator|new
name|File
argument_list|(
name|f
operator|.
name|getParentFile
argument_list|()
argument_list|,
literal|".$"
operator|+
name|f
operator|.
name|getName
argument_list|()
operator|+
literal|'$'
argument_list|)
return|;
block|}
comment|/**      * Check if a newer autosave exists for the given file.      * @param f The file to check.      * @return true if an autosave is found, and if the autosave is newer      *   than the given file.      */
DECL|method|newerAutoSaveExists (File f)
specifier|public
specifier|static
name|boolean
name|newerAutoSaveExists
parameter_list|(
name|File
name|f
parameter_list|)
block|{
name|File
name|asFile
init|=
name|getAutoSaveFile
argument_list|(
name|f
argument_list|)
decl_stmt|;
return|return
name|asFile
operator|.
name|exists
argument_list|()
operator|&&
operator|(
name|asFile
operator|.
name|lastModified
argument_list|()
operator|>
name|f
operator|.
name|lastModified
argument_list|()
operator|)
return|;
block|}
block|}
end_class

end_unit

