begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_package
DECL|package|net.sf.jabref.export
package|package
name|net
operator|.
name|sf
operator|.
name|jabref
operator|.
name|export
package|;
end_package

begin_import
import|import
name|javax
operator|.
name|swing
operator|.
name|filechooser
operator|.
name|FileFilter
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|File
import|;
end_import

begin_comment
comment|/**  * File filter that lets the user choose export format while choosing file to  * export to. Contains a reference to the ExportFormat in question.  */
end_comment

begin_class
DECL|class|ExportFileFilter
specifier|public
class|class
name|ExportFileFilter
extends|extends
name|FileFilter
block|{
DECL|field|format
specifier|private
name|ExportFormat
name|format
decl_stmt|;
DECL|field|extension
DECL|field|name
specifier|private
name|String
name|extension
decl_stmt|,
name|name
decl_stmt|;
DECL|method|ExportFileFilter (ExportFormat format)
specifier|public
name|ExportFileFilter
parameter_list|(
name|ExportFormat
name|format
parameter_list|)
block|{
name|this
operator|.
name|format
operator|=
name|format
expr_stmt|;
name|this
operator|.
name|extension
operator|=
name|format
operator|.
name|getExtension
argument_list|()
expr_stmt|;
name|this
operator|.
name|name
operator|=
name|format
operator|.
name|getDisplayName
argument_list|()
operator|+
literal|" (*"
operator|+
name|format
operator|.
name|getExtension
argument_list|()
operator|+
literal|")"
expr_stmt|;
block|}
DECL|method|getExportFormat ()
specifier|public
name|ExportFormat
name|getExportFormat
parameter_list|()
block|{
return|return
name|format
return|;
block|}
DECL|method|accept (File file)
specifier|public
name|boolean
name|accept
parameter_list|(
name|File
name|file
parameter_list|)
block|{
if|if
condition|(
name|file
operator|.
name|isDirectory
argument_list|()
condition|)
return|return
literal|true
return|;
else|else
return|return
name|file
operator|.
name|getPath
argument_list|()
operator|.
name|toLowerCase
argument_list|()
operator|.
name|endsWith
argument_list|(
name|extension
argument_list|)
return|;
block|}
DECL|method|getDescription ()
specifier|public
name|String
name|getDescription
parameter_list|()
block|{
return|return
name|name
return|;
block|}
block|}
end_class

end_unit

