begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_package
DECL|package|net.sf.jabref.logic.cleanup
package|package
name|net
operator|.
name|sf
operator|.
name|jabref
operator|.
name|logic
operator|.
name|cleanup
package|;
end_package

begin_import
import|import
name|net
operator|.
name|sf
operator|.
name|jabref
operator|.
name|logic
operator|.
name|formatter
operator|.
name|BibtexFieldFormatters
import|;
end_import

begin_import
import|import
name|net
operator|.
name|sf
operator|.
name|jabref
operator|.
name|model
operator|.
name|entry
operator|.
name|BibtexEntry
import|;
end_import

begin_comment
comment|/**  * This class includes sensible defaults for consistent formatting of BibTex page numbers.  */
end_comment

begin_class
DECL|class|PageNumbersCleanup
specifier|public
class|class
name|PageNumbersCleanup
block|{
DECL|field|entry
specifier|private
name|BibtexEntry
name|entry
decl_stmt|;
DECL|method|PageNumbersCleanup (BibtexEntry entry)
specifier|public
name|PageNumbersCleanup
parameter_list|(
name|BibtexEntry
name|entry
parameter_list|)
block|{
name|this
operator|.
name|entry
operator|=
name|entry
expr_stmt|;
block|}
comment|/**      * Format page numbers, separated either by commas or double-hyphens.      * Converts the range number format of the<code>pages</code> field to page_number--page_number.      *      * @see{PageNumbersFormatter}      */
DECL|method|cleanup ()
specifier|public
name|void
name|cleanup
parameter_list|()
block|{
specifier|final
name|String
name|field
init|=
literal|"pages"
decl_stmt|;
name|String
name|value
init|=
name|entry
operator|.
name|getField
argument_list|(
name|field
argument_list|)
decl_stmt|;
name|String
name|newValue
init|=
name|BibtexFieldFormatters
operator|.
name|PAGE_NUMBERS
operator|.
name|format
argument_list|(
name|value
argument_list|)
decl_stmt|;
name|entry
operator|.
name|setField
argument_list|(
name|field
argument_list|,
name|newValue
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

