begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_package
DECL|package|org.jabref.gui.shared
package|package
name|org
operator|.
name|jabref
operator|.
name|gui
operator|.
name|shared
package|;
end_package

begin_import
import|import
name|javax
operator|.
name|inject
operator|.
name|Inject
import|;
end_import

begin_import
import|import
name|javafx
operator|.
name|application
operator|.
name|Platform
import|;
end_import

begin_import
import|import
name|javafx
operator|.
name|event
operator|.
name|ActionEvent
import|;
end_import

begin_import
import|import
name|javafx
operator|.
name|fxml
operator|.
name|FXML
import|;
end_import

begin_import
import|import
name|javafx
operator|.
name|scene
operator|.
name|control
operator|.
name|Button
import|;
end_import

begin_import
import|import
name|javafx
operator|.
name|scene
operator|.
name|control
operator|.
name|ButtonType
import|;
end_import

begin_import
import|import
name|javafx
operator|.
name|scene
operator|.
name|control
operator|.
name|CheckBox
import|;
end_import

begin_import
import|import
name|javafx
operator|.
name|scene
operator|.
name|control
operator|.
name|ComboBox
import|;
end_import

begin_import
import|import
name|javafx
operator|.
name|scene
operator|.
name|control
operator|.
name|PasswordField
import|;
end_import

begin_import
import|import
name|javafx
operator|.
name|scene
operator|.
name|control
operator|.
name|TextField
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|gui
operator|.
name|DialogService
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|gui
operator|.
name|JabRefFrame
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|gui
operator|.
name|util
operator|.
name|BaseDialog
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|gui
operator|.
name|util
operator|.
name|ControlHelper
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|gui
operator|.
name|util
operator|.
name|IconValidationDecorator
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|logic
operator|.
name|l10n
operator|.
name|Localization
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|model
operator|.
name|database
operator|.
name|shared
operator|.
name|DBMSType
import|;
end_import

begin_import
import|import
name|com
operator|.
name|airhacks
operator|.
name|afterburner
operator|.
name|views
operator|.
name|ViewLoader
import|;
end_import

begin_import
import|import
name|de
operator|.
name|saxsys
operator|.
name|mvvmfx
operator|.
name|utils
operator|.
name|validation
operator|.
name|visualization
operator|.
name|ControlsFxVisualizer
import|;
end_import

begin_import
import|import
name|org
operator|.
name|fxmisc
operator|.
name|easybind
operator|.
name|EasyBind
import|;
end_import

begin_class
DECL|class|SharedDatabaseLoginDialogView
specifier|public
class|class
name|SharedDatabaseLoginDialogView
extends|extends
name|BaseDialog
argument_list|<
name|Void
argument_list|>
block|{
DECL|field|frame
specifier|private
specifier|final
name|JabRefFrame
name|frame
decl_stmt|;
DECL|field|databaseType
annotation|@
name|FXML
specifier|private
name|ComboBox
argument_list|<
name|DBMSType
argument_list|>
name|databaseType
decl_stmt|;
DECL|field|host
annotation|@
name|FXML
specifier|private
name|TextField
name|host
decl_stmt|;
DECL|field|database
annotation|@
name|FXML
specifier|private
name|TextField
name|database
decl_stmt|;
DECL|field|port
annotation|@
name|FXML
specifier|private
name|TextField
name|port
decl_stmt|;
DECL|field|user
annotation|@
name|FXML
specifier|private
name|TextField
name|user
decl_stmt|;
DECL|field|password
annotation|@
name|FXML
specifier|private
name|PasswordField
name|password
decl_stmt|;
DECL|field|rememberPassword
annotation|@
name|FXML
specifier|private
name|CheckBox
name|rememberPassword
decl_stmt|;
DECL|field|folder
annotation|@
name|FXML
specifier|private
name|TextField
name|folder
decl_stmt|;
DECL|field|browseButton
annotation|@
name|FXML
specifier|private
name|Button
name|browseButton
decl_stmt|;
DECL|field|autosave
annotation|@
name|FXML
specifier|private
name|CheckBox
name|autosave
decl_stmt|;
DECL|field|connectButton
annotation|@
name|FXML
specifier|private
name|ButtonType
name|connectButton
decl_stmt|;
DECL|field|useSSL
annotation|@
name|FXML
specifier|private
name|CheckBox
name|useSSL
decl_stmt|;
DECL|field|fileKeystore
annotation|@
name|FXML
specifier|private
name|TextField
name|fileKeystore
decl_stmt|;
DECL|field|passwordKeystore
annotation|@
name|FXML
specifier|private
name|PasswordField
name|passwordKeystore
decl_stmt|;
DECL|field|browseKeystore
annotation|@
name|FXML
specifier|private
name|Button
name|browseKeystore
decl_stmt|;
DECL|field|dialogService
annotation|@
name|Inject
specifier|private
name|DialogService
name|dialogService
decl_stmt|;
DECL|field|viewModel
specifier|private
name|SharedDatabaseLoginDialogViewModel
name|viewModel
decl_stmt|;
DECL|field|visualizer
specifier|private
specifier|final
name|ControlsFxVisualizer
name|visualizer
init|=
operator|new
name|ControlsFxVisualizer
argument_list|()
decl_stmt|;
DECL|method|SharedDatabaseLoginDialogView (JabRefFrame frame)
specifier|public
name|SharedDatabaseLoginDialogView
parameter_list|(
name|JabRefFrame
name|frame
parameter_list|)
block|{
name|this
operator|.
name|frame
operator|=
name|frame
expr_stmt|;
name|this
operator|.
name|setTitle
argument_list|(
name|Localization
operator|.
name|lang
argument_list|(
literal|"Connect to shared database"
argument_list|)
argument_list|)
expr_stmt|;
name|ViewLoader
operator|.
name|view
argument_list|(
name|this
argument_list|)
operator|.
name|load
argument_list|()
operator|.
name|setAsDialogPane
argument_list|(
name|this
argument_list|)
expr_stmt|;
name|ControlHelper
operator|.
name|setAction
argument_list|(
name|connectButton
argument_list|,
name|this
operator|.
name|getDialogPane
argument_list|()
argument_list|,
name|event
lambda|->
name|openDatabase
argument_list|()
argument_list|)
expr_stmt|;
name|Button
name|btnConnect
init|=
operator|(
name|Button
operator|)
name|this
operator|.
name|getDialogPane
argument_list|()
operator|.
name|lookupButton
argument_list|(
name|connectButton
argument_list|)
decl_stmt|;
comment|//must be set here, because in initialize the button is still null
name|btnConnect
operator|.
name|disableProperty
argument_list|()
operator|.
name|bind
argument_list|(
name|viewModel
operator|.
name|formValidation
argument_list|()
operator|.
name|validProperty
argument_list|()
operator|.
name|not
argument_list|()
argument_list|)
expr_stmt|;
name|btnConnect
operator|.
name|textProperty
argument_list|()
operator|.
name|bind
argument_list|(
name|EasyBind
operator|.
name|map
argument_list|(
name|viewModel
operator|.
name|loadingProperty
argument_list|()
argument_list|,
name|loading
lambda|->
operator|(
name|loading
operator|)
condition|?
name|Localization
operator|.
name|lang
argument_list|(
literal|"Connecting..."
argument_list|)
else|:
name|Localization
operator|.
name|lang
argument_list|(
literal|"Connect"
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
block|}
annotation|@
name|FXML
DECL|method|openDatabase ()
specifier|private
name|void
name|openDatabase
parameter_list|()
block|{
name|viewModel
operator|.
name|openDatabase
argument_list|()
expr_stmt|;
name|this
operator|.
name|close
argument_list|()
expr_stmt|;
block|}
annotation|@
name|FXML
DECL|method|initialize ()
specifier|private
name|void
name|initialize
parameter_list|()
block|{
name|visualizer
operator|.
name|setDecoration
argument_list|(
operator|new
name|IconValidationDecorator
argument_list|()
argument_list|)
expr_stmt|;
name|viewModel
operator|=
operator|new
name|SharedDatabaseLoginDialogViewModel
argument_list|(
name|frame
argument_list|,
name|dialogService
argument_list|)
expr_stmt|;
name|databaseType
operator|.
name|getItems
argument_list|()
operator|.
name|addAll
argument_list|(
name|DBMSType
operator|.
name|values
argument_list|()
argument_list|)
expr_stmt|;
name|databaseType
operator|.
name|getSelectionModel
argument_list|()
operator|.
name|select
argument_list|(
literal|0
argument_list|)
expr_stmt|;
name|database
operator|.
name|textProperty
argument_list|()
operator|.
name|bindBidirectional
argument_list|(
name|viewModel
operator|.
name|databaseproperty
argument_list|()
argument_list|)
expr_stmt|;
name|host
operator|.
name|textProperty
argument_list|()
operator|.
name|bindBidirectional
argument_list|(
name|viewModel
operator|.
name|hostProperty
argument_list|()
argument_list|)
expr_stmt|;
name|user
operator|.
name|textProperty
argument_list|()
operator|.
name|bindBidirectional
argument_list|(
name|viewModel
operator|.
name|userProperty
argument_list|()
argument_list|)
expr_stmt|;
name|password
operator|.
name|textProperty
argument_list|()
operator|.
name|bindBidirectional
argument_list|(
name|viewModel
operator|.
name|passwordProperty
argument_list|()
argument_list|)
expr_stmt|;
name|port
operator|.
name|textProperty
argument_list|()
operator|.
name|bindBidirectional
argument_list|(
name|viewModel
operator|.
name|portProperty
argument_list|()
argument_list|)
expr_stmt|;
name|databaseType
operator|.
name|valueProperty
argument_list|()
operator|.
name|bindBidirectional
argument_list|(
name|viewModel
operator|.
name|selectedDbmstypeProperty
argument_list|()
argument_list|)
expr_stmt|;
name|folder
operator|.
name|textProperty
argument_list|()
operator|.
name|bindBidirectional
argument_list|(
name|viewModel
operator|.
name|folderProperty
argument_list|()
argument_list|)
expr_stmt|;
name|browseButton
operator|.
name|disableProperty
argument_list|()
operator|.
name|bind
argument_list|(
name|viewModel
operator|.
name|autosaveProperty
argument_list|()
operator|.
name|not
argument_list|()
argument_list|)
expr_stmt|;
name|folder
operator|.
name|disableProperty
argument_list|()
operator|.
name|bind
argument_list|(
name|viewModel
operator|.
name|autosaveProperty
argument_list|()
operator|.
name|not
argument_list|()
argument_list|)
expr_stmt|;
name|autosave
operator|.
name|selectedProperty
argument_list|()
operator|.
name|bindBidirectional
argument_list|(
name|viewModel
operator|.
name|autosaveProperty
argument_list|()
argument_list|)
expr_stmt|;
name|useSSL
operator|.
name|selectedProperty
argument_list|()
operator|.
name|bindBidirectional
argument_list|(
name|viewModel
operator|.
name|useSSLProperty
argument_list|()
argument_list|)
expr_stmt|;
name|fileKeystore
operator|.
name|textProperty
argument_list|()
operator|.
name|bindBidirectional
argument_list|(
name|viewModel
operator|.
name|keyStoreProperty
argument_list|()
argument_list|)
expr_stmt|;
name|browseKeystore
operator|.
name|disableProperty
argument_list|()
operator|.
name|bind
argument_list|(
name|viewModel
operator|.
name|useSSLProperty
argument_list|()
operator|.
name|not
argument_list|()
argument_list|)
expr_stmt|;
name|passwordKeystore
operator|.
name|disableProperty
argument_list|()
operator|.
name|bind
argument_list|(
name|viewModel
operator|.
name|useSSLProperty
argument_list|()
operator|.
name|not
argument_list|()
argument_list|)
expr_stmt|;
name|passwordKeystore
operator|.
name|textProperty
argument_list|()
operator|.
name|bindBidirectional
argument_list|(
name|viewModel
operator|.
name|keyStorePasswordProperty
argument_list|()
argument_list|)
expr_stmt|;
comment|//Must be executed after the initialization of the view, otherwise it doesn't work
name|Platform
operator|.
name|runLater
argument_list|(
parameter_list|()
lambda|->
block|{
name|visualizer
operator|.
name|initVisualization
argument_list|(
name|viewModel
operator|.
name|dbValidation
argument_list|()
argument_list|,
name|database
argument_list|,
literal|true
argument_list|)
expr_stmt|;
name|visualizer
operator|.
name|initVisualization
argument_list|(
name|viewModel
operator|.
name|hostValidation
argument_list|()
argument_list|,
name|host
argument_list|,
literal|true
argument_list|)
expr_stmt|;
name|visualizer
operator|.
name|initVisualization
argument_list|(
name|viewModel
operator|.
name|portValidation
argument_list|()
argument_list|,
name|port
argument_list|,
literal|true
argument_list|)
expr_stmt|;
name|visualizer
operator|.
name|initVisualization
argument_list|(
name|viewModel
operator|.
name|userValidation
argument_list|()
argument_list|,
name|user
argument_list|,
literal|true
argument_list|)
expr_stmt|;
name|EasyBind
operator|.
name|subscribe
argument_list|(
name|autosave
operator|.
name|selectedProperty
argument_list|()
argument_list|,
name|selected
lambda|->
block|{
name|visualizer
operator|.
name|initVisualization
argument_list|(
name|viewModel
operator|.
name|folderValidation
argument_list|()
argument_list|,
name|folder
argument_list|,
literal|true
argument_list|)
expr_stmt|;
block|}
argument_list|)
expr_stmt|;
name|EasyBind
operator|.
name|subscribe
argument_list|(
name|useSSL
operator|.
name|selectedProperty
argument_list|()
argument_list|,
name|selected
lambda|->
block|{
name|visualizer
operator|.
name|initVisualization
argument_list|(
name|viewModel
operator|.
name|keystoreValidation
argument_list|()
argument_list|,
name|fileKeystore
argument_list|,
literal|true
argument_list|)
expr_stmt|;
block|}
argument_list|)
expr_stmt|;
block|}
argument_list|)
expr_stmt|;
block|}
annotation|@
name|FXML
DECL|method|showSaveDbToFileDialog (ActionEvent event)
specifier|private
name|void
name|showSaveDbToFileDialog
parameter_list|(
name|ActionEvent
name|event
parameter_list|)
block|{
name|viewModel
operator|.
name|showSaveDbToFileDialog
argument_list|()
expr_stmt|;
block|}
annotation|@
name|FXML
DECL|method|showOpenKeystoreFileDialog (ActionEvent event)
specifier|private
name|void
name|showOpenKeystoreFileDialog
parameter_list|(
name|ActionEvent
name|event
parameter_list|)
block|{
name|viewModel
operator|.
name|showOpenKeystoreFileDialog
argument_list|()
expr_stmt|;
block|}
block|}
end_class

end_unit

