begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_package
DECL|package|net.sf.jabref.model.bibtexkeypattern
package|package
name|net
operator|.
name|sf
operator|.
name|jabref
operator|.
name|model
operator|.
name|bibtexkeypattern
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_import
import|import
name|net
operator|.
name|sf
operator|.
name|jabref
operator|.
name|preferences
operator|.
name|JabRefPreferences
import|;
end_import

begin_class
DECL|class|DatabaseBibtexKeyPattern
specifier|public
class|class
name|DatabaseBibtexKeyPattern
extends|extends
name|AbstractBibtexKeyPattern
block|{
DECL|field|prefs
specifier|private
specifier|final
name|JabRefPreferences
name|prefs
decl_stmt|;
DECL|method|DatabaseBibtexKeyPattern (JabRefPreferences prefs)
specifier|public
name|DatabaseBibtexKeyPattern
parameter_list|(
name|JabRefPreferences
name|prefs
parameter_list|)
block|{
name|this
operator|.
name|prefs
operator|=
name|prefs
expr_stmt|;
block|}
annotation|@
name|Override
DECL|method|getLastLevelBibtexKeyPattern (String key)
specifier|public
name|List
argument_list|<
name|String
argument_list|>
name|getLastLevelBibtexKeyPattern
parameter_list|(
name|String
name|key
parameter_list|)
block|{
return|return
name|prefs
operator|.
name|getKeyPattern
argument_list|()
operator|.
name|getValue
argument_list|(
name|key
argument_list|)
return|;
block|}
block|}
end_class

end_unit

