begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_package
DECL|package|tests.net.sf.jabref
package|package
name|tests
operator|.
name|net
operator|.
name|sf
operator|.
name|jabref
package|;
end_package

begin_import
import|import
name|java
operator|.
name|awt
operator|.
name|Component
import|;
end_import

begin_import
import|import
name|java
operator|.
name|awt
operator|.
name|Container
import|;
end_import

begin_comment
comment|/**  * Provides helper methods for unit testing such as methods for making testing  * of GUIs easier.  *   * @author Dennis Hartrampf, Ines Moosdorf  */
end_comment

begin_class
DECL|class|TestUtils
specifier|public
class|class
name|TestUtils
block|{
comment|/** 	 * Get a Component by name. 	 *  	 * @param parent 	 *            The parent Component, where to search in. 	 * @param name 	 *            The name of the Component to find. 	 * @return The Component with the given name or null if no 	 *         such Component. 	 */
DECL|method|getChildNamed (Component parent, String name)
specifier|public
specifier|static
name|Component
name|getChildNamed
parameter_list|(
name|Component
name|parent
parameter_list|,
name|String
name|name
parameter_list|)
block|{
if|if
condition|(
name|name
operator|.
name|equals
argument_list|(
name|parent
operator|.
name|getName
argument_list|()
argument_list|)
condition|)
block|{
return|return
name|parent
return|;
block|}
if|if
condition|(
name|parent
operator|instanceof
name|Container
condition|)
block|{
name|Component
index|[]
name|children
init|=
operator|(
operator|(
name|Container
operator|)
name|parent
operator|)
operator|.
name|getComponents
argument_list|()
decl_stmt|;
for|for
control|(
name|int
name|i
init|=
literal|0
init|;
name|i
operator|<
name|children
operator|.
name|length
condition|;
operator|++
name|i
control|)
block|{
name|Component
name|child
init|=
name|getChildNamed
argument_list|(
name|children
index|[
name|i
index|]
argument_list|,
name|name
argument_list|)
decl_stmt|;
if|if
condition|(
name|child
operator|!=
literal|null
condition|)
block|{
return|return
name|child
return|;
block|}
block|}
block|}
return|return
literal|null
return|;
block|}
block|}
end_class

end_unit

