begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_package
DECL|package|net.sf.jabref
package|package
name|net
operator|.
name|sf
operator|.
name|jabref
package|;
end_package

begin_class
DECL|class|ToStringAutoCompleteFormater
specifier|public
class|class
name|ToStringAutoCompleteFormater
parameter_list|<
name|E
parameter_list|>
implements|implements
name|AutoCompleteFormater
argument_list|<
name|E
argument_list|>
block|{
annotation|@
name|Override
DECL|method|formatItemToString (E item)
specifier|public
name|String
name|formatItemToString
parameter_list|(
name|E
name|item
parameter_list|)
block|{
return|return
name|item
operator|.
name|toString
argument_list|()
return|;
block|}
block|}
end_class

end_unit

