begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_package
DECL|package|org.jabref.gui.externalfiletype
package|package
name|org
operator|.
name|jabref
operator|.
name|gui
operator|.
name|externalfiletype
package|;
end_package

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|testutils
operator|.
name|category
operator|.
name|GUITest
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Test
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|experimental
operator|.
name|categories
operator|.
name|Category
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|junit
operator|.
name|Assert
operator|.
name|assertNotNull
import|;
end_import

begin_class
annotation|@
name|Category
argument_list|(
name|GUITest
operator|.
name|class
argument_list|)
DECL|class|ExternalFileTypeTest
specifier|public
class|class
name|ExternalFileTypeTest
block|{
annotation|@
name|Test
DECL|method|getOpenWithApplicationMustNotReturnNull ()
specifier|public
name|void
name|getOpenWithApplicationMustNotReturnNull
parameter_list|()
throws|throws
name|Exception
block|{
name|ExternalFileType
name|type
init|=
operator|new
name|ExternalFileType
argument_list|(
literal|null
argument_list|,
literal|null
argument_list|,
literal|null
argument_list|,
literal|null
argument_list|,
literal|null
argument_list|,
literal|null
argument_list|)
decl_stmt|;
name|assertNotNull
argument_list|(
name|type
operator|.
name|getOpenWithApplication
argument_list|()
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
DECL|method|getExtensionMustNotReturnNull ()
specifier|public
name|void
name|getExtensionMustNotReturnNull
parameter_list|()
throws|throws
name|Exception
block|{
name|ExternalFileType
name|type
init|=
operator|new
name|ExternalFileType
argument_list|(
literal|null
argument_list|,
literal|null
argument_list|,
literal|null
argument_list|,
literal|null
argument_list|,
literal|null
argument_list|,
literal|null
argument_list|)
decl_stmt|;
name|assertNotNull
argument_list|(
name|type
operator|.
name|getExtension
argument_list|()
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
DECL|method|getMimeTypeMustNotReturnNull ()
specifier|public
name|void
name|getMimeTypeMustNotReturnNull
parameter_list|()
throws|throws
name|Exception
block|{
name|ExternalFileType
name|type
init|=
operator|new
name|ExternalFileType
argument_list|(
literal|null
argument_list|,
literal|null
argument_list|,
literal|null
argument_list|,
literal|null
argument_list|,
literal|null
argument_list|,
literal|null
argument_list|)
decl_stmt|;
name|assertNotNull
argument_list|(
name|type
operator|.
name|getMimeType
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

