begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_package
DECL|package|org.jabref.gui.texparser
package|package
name|org
operator|.
name|jabref
operator|.
name|gui
operator|.
name|texparser
package|;
end_package

begin_import
import|import
name|java
operator|.
name|nio
operator|.
name|file
operator|.
name|Path
import|;
end_import

begin_import
import|import
name|javafx
operator|.
name|fxml
operator|.
name|FXML
import|;
end_import

begin_import
import|import
name|javafx
operator|.
name|scene
operator|.
name|control
operator|.
name|Button
import|;
end_import

begin_import
import|import
name|javafx
operator|.
name|scene
operator|.
name|control
operator|.
name|ButtonType
import|;
end_import

begin_import
import|import
name|javafx
operator|.
name|scene
operator|.
name|control
operator|.
name|ListView
import|;
end_import

begin_import
import|import
name|javafx
operator|.
name|scene
operator|.
name|text
operator|.
name|Text
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|gui
operator|.
name|util
operator|.
name|BaseDialog
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|gui
operator|.
name|util
operator|.
name|ControlHelper
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|gui
operator|.
name|util
operator|.
name|ViewModelListCellFactory
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|logic
operator|.
name|l10n
operator|.
name|Localization
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|model
operator|.
name|database
operator|.
name|BibDatabaseContext
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|model
operator|.
name|texparser
operator|.
name|TexBibEntriesResolverResult
import|;
end_import

begin_import
import|import
name|com
operator|.
name|airhacks
operator|.
name|afterburner
operator|.
name|views
operator|.
name|ViewLoader
import|;
end_import

begin_import
import|import
name|org
operator|.
name|fxmisc
operator|.
name|easybind
operator|.
name|EasyBind
import|;
end_import

begin_class
DECL|class|ParseTexResultView
specifier|public
class|class
name|ParseTexResultView
extends|extends
name|BaseDialog
argument_list|<
name|Void
argument_list|>
block|{
DECL|field|resolverResult
specifier|private
specifier|final
name|TexBibEntriesResolverResult
name|resolverResult
decl_stmt|;
DECL|field|databaseContext
specifier|private
specifier|final
name|BibDatabaseContext
name|databaseContext
decl_stmt|;
DECL|field|basePath
specifier|private
specifier|final
name|Path
name|basePath
decl_stmt|;
DECL|field|referenceListView
annotation|@
name|FXML
specifier|private
name|ListView
argument_list|<
name|ReferenceViewModel
argument_list|>
name|referenceListView
decl_stmt|;
DECL|field|citationsDisplay
annotation|@
name|FXML
specifier|private
name|CitationsDisplay
name|citationsDisplay
decl_stmt|;
DECL|field|importButtonType
annotation|@
name|FXML
specifier|private
name|ButtonType
name|importButtonType
decl_stmt|;
DECL|field|viewModel
specifier|private
name|ParseTexResultViewModel
name|viewModel
decl_stmt|;
DECL|method|ParseTexResultView (TexBibEntriesResolverResult resolverResult, BibDatabaseContext databaseContext, Path basePath)
specifier|public
name|ParseTexResultView
parameter_list|(
name|TexBibEntriesResolverResult
name|resolverResult
parameter_list|,
name|BibDatabaseContext
name|databaseContext
parameter_list|,
name|Path
name|basePath
parameter_list|)
block|{
name|this
operator|.
name|resolverResult
operator|=
name|resolverResult
expr_stmt|;
name|this
operator|.
name|databaseContext
operator|=
name|databaseContext
expr_stmt|;
name|this
operator|.
name|basePath
operator|=
name|basePath
expr_stmt|;
name|setTitle
argument_list|(
name|Localization
operator|.
name|lang
argument_list|(
literal|"LaTeX Citations Search Results"
argument_list|)
argument_list|)
expr_stmt|;
name|ViewLoader
operator|.
name|view
argument_list|(
name|this
argument_list|)
operator|.
name|load
argument_list|()
operator|.
name|setAsDialogPane
argument_list|(
name|this
argument_list|)
expr_stmt|;
name|ControlHelper
operator|.
name|setAction
argument_list|(
name|importButtonType
argument_list|,
name|getDialogPane
argument_list|()
argument_list|,
name|event
lambda|->
block|{
name|viewModel
operator|.
name|importButtonClicked
argument_list|()
expr_stmt|;
name|close
argument_list|()
expr_stmt|;
block|}
argument_list|)
expr_stmt|;
name|Button
name|importButton
init|=
operator|(
name|Button
operator|)
name|getDialogPane
argument_list|()
operator|.
name|lookupButton
argument_list|(
name|importButtonType
argument_list|)
decl_stmt|;
name|importButton
operator|.
name|disableProperty
argument_list|()
operator|.
name|bind
argument_list|(
name|viewModel
operator|.
name|importButtonDisabledProperty
argument_list|()
argument_list|)
expr_stmt|;
block|}
annotation|@
name|FXML
DECL|method|initialize ()
specifier|private
name|void
name|initialize
parameter_list|()
block|{
name|viewModel
operator|=
operator|new
name|ParseTexResultViewModel
argument_list|(
name|resolverResult
argument_list|,
name|databaseContext
argument_list|)
expr_stmt|;
name|referenceListView
operator|.
name|setItems
argument_list|(
name|viewModel
operator|.
name|getReferenceList
argument_list|()
argument_list|)
expr_stmt|;
name|referenceListView
operator|.
name|getSelectionModel
argument_list|()
operator|.
name|selectFirst
argument_list|()
expr_stmt|;
operator|new
name|ViewModelListCellFactory
argument_list|<
name|ReferenceViewModel
argument_list|>
argument_list|()
operator|.
name|withGraphic
argument_list|(
name|reference
lambda|->
block|{
name|Text
name|referenceText
init|=
operator|new
name|Text
argument_list|(
name|reference
operator|.
name|getDisplayText
argument_list|()
argument_list|)
decl_stmt|;
if|if
condition|(
name|reference
operator|.
name|isHighlighted
argument_list|()
condition|)
block|{
name|referenceText
operator|.
name|setStyle
argument_list|(
literal|"-fx-fill: -fx-accent"
argument_list|)
expr_stmt|;
block|}
return|return
name|referenceText
return|;
block|}
argument_list|)
operator|.
name|install
argument_list|(
name|referenceListView
argument_list|)
expr_stmt|;
name|EasyBind
operator|.
name|subscribe
argument_list|(
name|referenceListView
operator|.
name|getSelectionModel
argument_list|()
operator|.
name|selectedItemProperty
argument_list|()
argument_list|,
name|viewModel
operator|::
name|activeReferenceChanged
argument_list|)
expr_stmt|;
name|citationsDisplay
operator|.
name|basePathProperty
argument_list|()
operator|.
name|set
argument_list|(
name|basePath
argument_list|)
expr_stmt|;
name|citationsDisplay
operator|.
name|setItems
argument_list|(
name|viewModel
operator|.
name|getCitationListByReference
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

