# Configuration for https://dependabot.com
version: 1

update_configs:
  - package_manager: "java:gradle"
    directory: "/"
    update_schedule: "weekly"
    
  - package_manager: "submodules"
    directory: "/"
    update_schedule: "weekly"
