begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_package
DECL|package|net.sf.jabref.gui
package|package
name|net
operator|.
name|sf
operator|.
name|jabref
operator|.
name|gui
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Optional
import|;
end_import

begin_import
import|import
name|javafx
operator|.
name|beans
operator|.
name|property
operator|.
name|ObjectProperty
import|;
end_import

begin_import
import|import
name|javafx
operator|.
name|beans
operator|.
name|property
operator|.
name|SimpleObjectProperty
import|;
end_import

begin_import
import|import
name|javafx
operator|.
name|collections
operator|.
name|FXCollections
import|;
end_import

begin_import
import|import
name|javafx
operator|.
name|collections
operator|.
name|ObservableList
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|model
operator|.
name|database
operator|.
name|BibDatabaseContext
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|model
operator|.
name|entry
operator|.
name|BibEntry
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|model
operator|.
name|groups
operator|.
name|GroupTreeNode
import|;
end_import

begin_comment
comment|/**  * This class manages the GUI-state of JabRef, including:  * - currently selected database  * - currently selected group  * Coming soon:  * - open databases  * - active search  */
end_comment

begin_class
DECL|class|StateManager
specifier|public
class|class
name|StateManager
block|{
DECL|field|activeDatabase
specifier|private
specifier|final
name|ObjectProperty
argument_list|<
name|Optional
argument_list|<
name|BibDatabaseContext
argument_list|>
argument_list|>
name|activeDatabase
init|=
operator|new
name|SimpleObjectProperty
argument_list|<>
argument_list|(
name|Optional
operator|.
name|empty
argument_list|()
argument_list|)
decl_stmt|;
DECL|field|activeGroup
specifier|private
specifier|final
name|ObjectProperty
argument_list|<
name|Optional
argument_list|<
name|GroupTreeNode
argument_list|>
argument_list|>
name|activeGroup
init|=
operator|new
name|SimpleObjectProperty
argument_list|<>
argument_list|(
name|Optional
operator|.
name|empty
argument_list|()
argument_list|)
decl_stmt|;
DECL|field|selectedEntries
specifier|private
specifier|final
name|ObservableList
argument_list|<
name|BibEntry
argument_list|>
name|selectedEntries
init|=
name|FXCollections
operator|.
name|observableArrayList
argument_list|()
decl_stmt|;
DECL|method|activeDatabaseProperty ()
specifier|public
name|ObjectProperty
argument_list|<
name|Optional
argument_list|<
name|BibDatabaseContext
argument_list|>
argument_list|>
name|activeDatabaseProperty
parameter_list|()
block|{
return|return
name|activeDatabase
return|;
block|}
DECL|method|activeGroupProperty ()
specifier|public
name|ObjectProperty
argument_list|<
name|Optional
argument_list|<
name|GroupTreeNode
argument_list|>
argument_list|>
name|activeGroupProperty
parameter_list|()
block|{
return|return
name|activeGroup
return|;
block|}
DECL|method|getSelectedEntries ()
specifier|public
name|ObservableList
argument_list|<
name|BibEntry
argument_list|>
name|getSelectedEntries
parameter_list|()
block|{
return|return
name|FXCollections
operator|.
name|unmodifiableObservableList
argument_list|(
name|selectedEntries
argument_list|)
return|;
block|}
DECL|method|setSelectedEntries (List<BibEntry> newSelectedEntries)
specifier|public
name|void
name|setSelectedEntries
parameter_list|(
name|List
argument_list|<
name|BibEntry
argument_list|>
name|newSelectedEntries
parameter_list|)
block|{
name|selectedEntries
operator|.
name|clear
argument_list|()
expr_stmt|;
name|selectedEntries
operator|.
name|addAll
argument_list|(
name|newSelectedEntries
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

