begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_package
DECL|package|antlr
package|package
name|antlr
package|;
end_package

begin_comment
comment|/* ANTLR Translator Generator  * Project led by Terence Parr at http://www.jGuru.com  * Software rights: http://www.antlr.org/RIGHTS.html  *  * $Id$  */
end_comment

begin_class
DECL|class|TokenRefElement
class|class
name|TokenRefElement
extends|extends
name|GrammarAtom
block|{
DECL|method|TokenRefElement (Grammar g, Token t, boolean inverted, int autoGenType)
specifier|public
name|TokenRefElement
parameter_list|(
name|Grammar
name|g
parameter_list|,
name|Token
name|t
parameter_list|,
name|boolean
name|inverted
parameter_list|,
name|int
name|autoGenType
parameter_list|)
block|{
name|super
argument_list|(
name|g
argument_list|,
name|t
argument_list|,
name|autoGenType
argument_list|)
expr_stmt|;
name|not
operator|=
name|inverted
expr_stmt|;
name|TokenSymbol
name|ts
init|=
name|grammar
operator|.
name|tokenManager
operator|.
name|getTokenSymbol
argument_list|(
name|atomText
argument_list|)
decl_stmt|;
if|if
condition|(
name|ts
operator|==
literal|null
condition|)
block|{
name|g
operator|.
name|tool
operator|.
name|error
argument_list|(
literal|"Undefined token symbol: "
operator|+
name|atomText
argument_list|,
name|grammar
operator|.
name|getFilename
argument_list|()
argument_list|,
name|t
operator|.
name|getLine
argument_list|()
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|tokenType
operator|=
name|ts
operator|.
name|getTokenType
argument_list|()
expr_stmt|;
comment|// set the AST node type to whatever was set in tokens {...}
comment|// section (if anything);
comment|// Lafter, after this is created, the element option can set this.
name|setASTNodeType
argument_list|(
name|ts
operator|.
name|getASTNodeType
argument_list|()
argument_list|)
expr_stmt|;
block|}
name|line
operator|=
name|t
operator|.
name|getLine
argument_list|()
expr_stmt|;
block|}
DECL|method|generate ()
specifier|public
name|void
name|generate
parameter_list|()
block|{
name|grammar
operator|.
name|generator
operator|.
name|gen
argument_list|(
name|this
argument_list|)
expr_stmt|;
block|}
DECL|method|look (int k)
specifier|public
name|Lookahead
name|look
parameter_list|(
name|int
name|k
parameter_list|)
block|{
return|return
name|grammar
operator|.
name|theLLkAnalyzer
operator|.
name|look
argument_list|(
name|k
argument_list|,
name|this
argument_list|)
return|;
block|}
block|}
end_class

end_unit

