begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_package
DECL|package|org.jabref.logic.exporter
package|package
name|org
operator|.
name|jabref
operator|.
name|logic
operator|.
name|exporter
package|;
end_package

begin_import
import|import
name|java
operator|.
name|nio
operator|.
name|charset
operator|.
name|Charset
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Collections
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|logic
operator|.
name|bibtex
operator|.
name|LatexFieldFormatterPreferences
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|model
operator|.
name|bibtexkeypattern
operator|.
name|GlobalBibtexKeyPattern
import|;
end_import

begin_import
import|import
name|org
operator|.
name|jabref
operator|.
name|model
operator|.
name|metadata
operator|.
name|SaveOrderConfig
import|;
end_import

begin_class
DECL|class|SavePreferences
specifier|public
class|class
name|SavePreferences
block|{
comment|// Encoding written at the top of the .bib file.
DECL|field|ENCODING_PREFIX
specifier|public
specifier|static
specifier|final
name|String
name|ENCODING_PREFIX
init|=
literal|"Encoding: "
decl_stmt|;
DECL|field|reformatFile
specifier|private
specifier|final
name|boolean
name|reformatFile
decl_stmt|;
DECL|field|saveInOriginalOrder
specifier|private
specifier|final
name|boolean
name|saveInOriginalOrder
decl_stmt|;
DECL|field|saveOrder
specifier|private
specifier|final
name|SaveOrderConfig
name|saveOrder
decl_stmt|;
DECL|field|encoding
specifier|private
specifier|final
name|Charset
name|encoding
decl_stmt|;
DECL|field|makeBackup
specifier|private
specifier|final
name|boolean
name|makeBackup
decl_stmt|;
DECL|field|saveType
specifier|private
specifier|final
name|DatabaseSaveType
name|saveType
decl_stmt|;
DECL|field|takeMetadataSaveOrderInAccount
specifier|private
specifier|final
name|boolean
name|takeMetadataSaveOrderInAccount
decl_stmt|;
DECL|field|latexFieldFormatterPreferences
specifier|private
specifier|final
name|LatexFieldFormatterPreferences
name|latexFieldFormatterPreferences
decl_stmt|;
DECL|field|globalCiteKeyPattern
specifier|private
specifier|final
name|GlobalBibtexKeyPattern
name|globalCiteKeyPattern
decl_stmt|;
DECL|method|SavePreferences ()
specifier|public
name|SavePreferences
parameter_list|()
block|{
name|this
argument_list|(
literal|true
argument_list|,
literal|null
argument_list|,
literal|null
argument_list|,
literal|false
argument_list|,
name|DatabaseSaveType
operator|.
name|ALL
argument_list|,
literal|true
argument_list|,
literal|false
argument_list|,
operator|new
name|LatexFieldFormatterPreferences
argument_list|()
argument_list|,
operator|new
name|GlobalBibtexKeyPattern
argument_list|(
name|Collections
operator|.
name|emptyList
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
block|}
DECL|method|SavePreferences (Boolean saveInOriginalOrder, SaveOrderConfig saveOrder, Charset encoding, Boolean makeBackup, DatabaseSaveType saveType, Boolean takeMetadataSaveOrderInAccount, Boolean reformatFile, LatexFieldFormatterPreferences latexFieldFormatterPreferences, GlobalBibtexKeyPattern globalCiteKeyPattern)
specifier|public
name|SavePreferences
parameter_list|(
name|Boolean
name|saveInOriginalOrder
parameter_list|,
name|SaveOrderConfig
name|saveOrder
parameter_list|,
name|Charset
name|encoding
parameter_list|,
name|Boolean
name|makeBackup
parameter_list|,
name|DatabaseSaveType
name|saveType
parameter_list|,
name|Boolean
name|takeMetadataSaveOrderInAccount
parameter_list|,
name|Boolean
name|reformatFile
parameter_list|,
name|LatexFieldFormatterPreferences
name|latexFieldFormatterPreferences
parameter_list|,
name|GlobalBibtexKeyPattern
name|globalCiteKeyPattern
parameter_list|)
block|{
name|this
operator|.
name|saveInOriginalOrder
operator|=
name|saveInOriginalOrder
expr_stmt|;
name|this
operator|.
name|saveOrder
operator|=
name|saveOrder
expr_stmt|;
name|this
operator|.
name|encoding
operator|=
name|encoding
expr_stmt|;
name|this
operator|.
name|makeBackup
operator|=
name|makeBackup
expr_stmt|;
name|this
operator|.
name|saveType
operator|=
name|saveType
expr_stmt|;
name|this
operator|.
name|takeMetadataSaveOrderInAccount
operator|=
name|takeMetadataSaveOrderInAccount
expr_stmt|;
name|this
operator|.
name|reformatFile
operator|=
name|reformatFile
expr_stmt|;
name|this
operator|.
name|latexFieldFormatterPreferences
operator|=
name|latexFieldFormatterPreferences
expr_stmt|;
name|this
operator|.
name|globalCiteKeyPattern
operator|=
name|globalCiteKeyPattern
expr_stmt|;
block|}
DECL|method|getTakeMetadataSaveOrderInAccount ()
specifier|public
name|Boolean
name|getTakeMetadataSaveOrderInAccount
parameter_list|()
block|{
return|return
name|takeMetadataSaveOrderInAccount
return|;
block|}
DECL|method|getSaveOrder ()
specifier|public
name|SaveOrderConfig
name|getSaveOrder
parameter_list|()
block|{
return|return
name|saveOrder
return|;
block|}
DECL|method|isSaveInOriginalOrder ()
specifier|public
name|boolean
name|isSaveInOriginalOrder
parameter_list|()
block|{
return|return
name|saveInOriginalOrder
return|;
block|}
DECL|method|withSaveInOriginalOrder (Boolean newSaveInOriginalOrder)
specifier|public
name|SavePreferences
name|withSaveInOriginalOrder
parameter_list|(
name|Boolean
name|newSaveInOriginalOrder
parameter_list|)
block|{
return|return
operator|new
name|SavePreferences
argument_list|(
name|newSaveInOriginalOrder
argument_list|,
name|this
operator|.
name|saveOrder
argument_list|,
name|this
operator|.
name|encoding
argument_list|,
name|this
operator|.
name|makeBackup
argument_list|,
name|this
operator|.
name|saveType
argument_list|,
name|this
operator|.
name|takeMetadataSaveOrderInAccount
argument_list|,
name|this
operator|.
name|reformatFile
argument_list|,
name|this
operator|.
name|latexFieldFormatterPreferences
argument_list|,
name|globalCiteKeyPattern
argument_list|)
return|;
block|}
DECL|method|getMakeBackup ()
specifier|public
name|boolean
name|getMakeBackup
parameter_list|()
block|{
return|return
name|makeBackup
return|;
block|}
DECL|method|withMakeBackup (Boolean newMakeBackup)
specifier|public
name|SavePreferences
name|withMakeBackup
parameter_list|(
name|Boolean
name|newMakeBackup
parameter_list|)
block|{
return|return
operator|new
name|SavePreferences
argument_list|(
name|this
operator|.
name|saveInOriginalOrder
argument_list|,
name|this
operator|.
name|saveOrder
argument_list|,
name|this
operator|.
name|encoding
argument_list|,
name|newMakeBackup
argument_list|,
name|this
operator|.
name|saveType
argument_list|,
name|this
operator|.
name|takeMetadataSaveOrderInAccount
argument_list|,
name|this
operator|.
name|reformatFile
argument_list|,
name|this
operator|.
name|latexFieldFormatterPreferences
argument_list|,
name|globalCiteKeyPattern
argument_list|)
return|;
block|}
DECL|method|getEncoding ()
specifier|public
name|Charset
name|getEncoding
parameter_list|()
block|{
return|return
name|encoding
return|;
block|}
DECL|method|withEncoding (Charset newEncoding)
specifier|public
name|SavePreferences
name|withEncoding
parameter_list|(
name|Charset
name|newEncoding
parameter_list|)
block|{
return|return
operator|new
name|SavePreferences
argument_list|(
name|this
operator|.
name|saveInOriginalOrder
argument_list|,
name|this
operator|.
name|saveOrder
argument_list|,
name|newEncoding
argument_list|,
name|this
operator|.
name|makeBackup
argument_list|,
name|this
operator|.
name|saveType
argument_list|,
name|this
operator|.
name|takeMetadataSaveOrderInAccount
argument_list|,
name|this
operator|.
name|reformatFile
argument_list|,
name|this
operator|.
name|latexFieldFormatterPreferences
argument_list|,
name|globalCiteKeyPattern
argument_list|)
return|;
block|}
DECL|method|getSaveType ()
specifier|public
name|DatabaseSaveType
name|getSaveType
parameter_list|()
block|{
return|return
name|saveType
return|;
block|}
DECL|method|withSaveType (DatabaseSaveType newSaveType)
specifier|public
name|SavePreferences
name|withSaveType
parameter_list|(
name|DatabaseSaveType
name|newSaveType
parameter_list|)
block|{
return|return
operator|new
name|SavePreferences
argument_list|(
name|this
operator|.
name|saveInOriginalOrder
argument_list|,
name|this
operator|.
name|saveOrder
argument_list|,
name|this
operator|.
name|encoding
argument_list|,
name|this
operator|.
name|makeBackup
argument_list|,
name|newSaveType
argument_list|,
name|this
operator|.
name|takeMetadataSaveOrderInAccount
argument_list|,
name|this
operator|.
name|reformatFile
argument_list|,
name|this
operator|.
name|latexFieldFormatterPreferences
argument_list|,
name|globalCiteKeyPattern
argument_list|)
return|;
block|}
DECL|method|isReformatFile ()
specifier|public
name|Boolean
name|isReformatFile
parameter_list|()
block|{
return|return
name|reformatFile
return|;
block|}
DECL|method|withReformatFile (boolean newReformatFile)
specifier|public
name|SavePreferences
name|withReformatFile
parameter_list|(
name|boolean
name|newReformatFile
parameter_list|)
block|{
return|return
operator|new
name|SavePreferences
argument_list|(
name|this
operator|.
name|saveInOriginalOrder
argument_list|,
name|this
operator|.
name|saveOrder
argument_list|,
name|this
operator|.
name|encoding
argument_list|,
name|this
operator|.
name|makeBackup
argument_list|,
name|this
operator|.
name|saveType
argument_list|,
name|this
operator|.
name|takeMetadataSaveOrderInAccount
argument_list|,
name|newReformatFile
argument_list|,
name|this
operator|.
name|latexFieldFormatterPreferences
argument_list|,
name|globalCiteKeyPattern
argument_list|)
return|;
block|}
DECL|method|getEncodingOrDefault ()
specifier|public
name|Charset
name|getEncodingOrDefault
parameter_list|()
block|{
return|return
name|encoding
operator|==
literal|null
condition|?
name|Charset
operator|.
name|defaultCharset
argument_list|()
else|:
name|encoding
return|;
block|}
DECL|method|getLatexFieldFormatterPreferences ()
specifier|public
name|LatexFieldFormatterPreferences
name|getLatexFieldFormatterPreferences
parameter_list|()
block|{
return|return
name|latexFieldFormatterPreferences
return|;
block|}
DECL|method|getGlobalCiteKeyPattern ()
specifier|public
name|GlobalBibtexKeyPattern
name|getGlobalCiteKeyPattern
parameter_list|()
block|{
return|return
name|globalCiteKeyPattern
return|;
block|}
DECL|enum|DatabaseSaveType
specifier|public
enum|enum
name|DatabaseSaveType
block|{
DECL|enumConstant|ALL
name|ALL
block|,
DECL|enumConstant|PLAIN_BIBTEX
name|PLAIN_BIBTEX
block|}
block|}
end_class

end_unit

